import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { VariableTask, ScheduleOccurrence } from "./types";
import { getDaysLeft } from "./types";

/**
 * Export Monthly Calendar as PDF
 */
export function exportMonthlyCalendarPdf(
  tasks: VariableTask[],
  schedule: ScheduleOccurrence[],
  year: number,
  month: number, // 0-indexed
) {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const monthNames = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
  const dayNames = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

  // Title
  doc.setFontSize(18);
  doc.setTextColor(13, 148, 136); // teal
  doc.text(`MONTHLY CALENDAR — ${monthNames[month]} ${year}`, 14, 15);

  // Calendar grid
  const firstDay = new Date(year, month, 1);
  const lastDay = new Date(year, month + 1, 0);
  const startOffset = firstDay.getDay();
  const daysInMonth = lastDay.getDate();

  const prefix = `${year}-${String(month + 1).padStart(2, "0")}`;
  const allTasks = [
    ...tasks.filter(t => (t.due_date || "").startsWith(prefix)).map(t => ({ name: t.task_name, date: t.due_date || "", done: t.is_completed })),
    ...schedule.filter(s => s.occurrence_date.startsWith(prefix)).map(s => ({ name: s.task_name || "", date: s.occurrence_date, done: s.is_done })),
  ];

  // Build table data (7 columns)
  const rows: string[][] = [];
  let currentRow: string[] = [];

  // Fill empty start cells
  for (let i = 0; i < startOffset; i++) currentRow.push("");

  for (let d = 1; d <= daysInMonth; d++) {
    const dateStr = `${year}-${String(month + 1).padStart(2, "0")}-${String(d).padStart(2, "0")}`;
    const dayTasks = allTasks.filter(t => t.date === dateStr);
    const taskList = dayTasks.slice(0, 3).map(t => `${t.done ? "✓ " : ""}${t.name}`).join("\n");
    currentRow.push(`${d}\n${taskList}`);

    if (currentRow.length === 7) {
      rows.push(currentRow);
      currentRow = [];
    }
  }
  if (currentRow.length > 0) {
    while (currentRow.length < 7) currentRow.push("");
    rows.push(currentRow);
  }

  autoTable(doc, {
    head: [dayNames],
    body: rows,
    startY: 22,
    theme: "grid",
    styles: { fontSize: 7, cellPadding: 2, valign: "top", minCellHeight: 18 },
    headStyles: { fillColor: [13, 148, 136], textColor: 255, fontSize: 8 },
    columnStyles: { 0: { cellWidth: 38 }, 1: { cellWidth: 38 }, 2: { cellWidth: 38 }, 3: { cellWidth: 38 }, 4: { cellWidth: 38 }, 5: { cellWidth: 38 }, 6: { cellWidth: 38 } },
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(128);
  doc.text(`Generated by Ayuzee Task Tracker · ${new Date().toLocaleDateString()}`, 14, doc.internal.pageSize.height - 8);

  doc.save(`Monthly_Calendar_${monthNames[month]}_${year}.pdf`);
}

/**
 * Export Gantt Chart as PDF
 */
export function exportGanttPdf(
  tasks: VariableTask[],
  projectName: string,
  projectManager: string,
) {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });

  // Title
  doc.setFontSize(16);
  doc.setTextColor(13, 148, 136);
  doc.text(`GANTT CHART — ${projectName}`, 14, 15);
  doc.setFontSize(9);
  doc.setTextColor(100);
  doc.text(`Project Manager: ${projectManager} | Generated: ${new Date().toLocaleDateString()}`, 14, 21);

  // Filter tasks with dates
  const ganttTasks = tasks.filter(t => t.start_date && t.due_date);

  const tableData = ganttTasks.map(t => {
    const start = new Date(t.start_date!);
    const end = new Date(t.due_date!);
    const duration = Math.ceil((end.getTime() - start.getTime()) / (1000 * 60 * 60 * 24));
    const daysLeft = getDaysLeft(t.due_date);
    let status = "In Progress";
    if (t.is_completed || t.progress >= 100) status = "Completed";
    else if (daysLeft !== null && daysLeft < 0) status = "Delayed";
    else if (t.priority === "On Hold") status = "On Hold";

    return [
      t.task_name,
      `${t.progress}%`,
      t.start_date || "",
      t.due_date || "",
      `${duration}d`,
      t.priority,
      t.person_in_charge,
      status,
      daysLeft !== null ? String(daysLeft) : "—",
    ];
  });

  autoTable(doc, {
    head: [["Task", "Progress", "Start", "End", "Duration", "Priority", "Person", "Status", "Days Left"]],
    body: tableData,
    startY: 26,
    theme: "striped",
    styles: { fontSize: 7, cellPadding: 2 },
    headStyles: { fillColor: [13, 148, 136], textColor: 255, fontSize: 8 },
    columnStyles: {
      0: { cellWidth: 50 },
      7: { cellWidth: 22 },
    },
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(128);
  doc.text(`Ayuzee Task Tracker · Total tasks: ${ganttTasks.length}`, 14, doc.internal.pageSize.height - 8);

  doc.save(`Gantt_Chart_${projectName.replace(/\s+/g, "_")}.pdf`);
}

/**
 * Export Variable Tasks as PDF table
 */
export function exportTaskListPdf(tasks: VariableTask[]) {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });

  doc.setFontSize(16);
  doc.setTextColor(13, 148, 136);
  doc.text("VARIABLE TASKS", 14, 15);

  const tableData = tasks.map(t => [
    t.is_completed ? "✓" : "",
    t.task_name,
    t.status,
    t.priority,
    t.person_in_charge,
    t.start_date || "—",
    t.due_date || "—",
    t.kanban_category,
    t.decision,
    `${t.progress}%`,
  ]);

  autoTable(doc, {
    head: [["Done", "Task", "Status", "Priority", "Person", "Start", "Due", "Category", "Decision", "Progress"]],
    body: tableData,
    startY: 22,
    theme: "striped",
    styles: { fontSize: 7, cellPadding: 1.5 },
    headStyles: { fillColor: [13, 148, 136], textColor: 255, fontSize: 7 },
  });

  doc.setFontSize(8);
  doc.setTextColor(128);
  doc.text(`Ayuzee Task Tracker · ${tasks.length} tasks · ${new Date().toLocaleDateString()}`, 14, doc.internal.pageSize.height - 8);

  doc.save(`Tasks_Export_${new Date().toISOString().split("T")[0]}.pdf`);
}
