import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

// Brand palette (matches homeo Reports.tsx pattern)
const HEADER_BG: [number, number, number] = [20, 50, 35];
const HEADER_FG: [number, number, number] = [220, 180, 90];
const TEXT_DARK: [number, number, number] = [40, 40, 40];
const MUTED: [number, number, number] = [120, 120, 120];

export interface PdfHeader {
  clinicName?: string;
  doctorName?: string;
  regNo?: string;
  subtitle?: string; // shown small, e.g. "Tax Invoice"
}

export interface SectionTable {
  title?: string;
  head?: string[];
  body: (string | number)[][];
  columnStyles?: Record<number, any>;
}

/**
 * Create a jsPDF doc with the Ayuzee branded header and return it
 * along with the y-cursor positioned just below the header.
 */
export function startAyuzeePdf(header: PdfHeader = {}): { doc: jsPDF; y: number; W: number } {
  const doc = new jsPDF();
  const W = doc.internal.pageSize.getWidth();

  doc.setFillColor(...HEADER_BG);
  doc.rect(0, 0, W, 28, "F");
  doc.setTextColor(...HEADER_FG);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text(header.clinicName || "Ayuzee", W / 2, 14, { align: "center" });
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  const sub = [
    header.doctorName ? `Dr. ${header.doctorName}` : null,
    header.regNo ? `Reg ${header.regNo}` : null,
    header.subtitle || null,
  ]
    .filter(Boolean)
    .join(" · ");
  if (sub) doc.text(sub, W / 2, 22, { align: "center" });

  return { doc, y: 38, W };
}

export function addTitle(doc: jsPDF, y: number, title: string, dateText?: string): number {
  const W = doc.internal.pageSize.getWidth();
  doc.setTextColor(...TEXT_DARK);
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.text(title, 14, y);
  if (dateText) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(dateText, W - 14, y, { align: "right" });
  }
  return y + 4;
}

export function addPlainTable(doc: jsPDF, y: number, body: (string | number)[][]): number {
  autoTable(doc, {
    startY: y,
    theme: "plain",
    styles: { fontSize: 10, cellPadding: 1.5 },
    body: body.map((r) => r.map((c) => (c == null ? "—" : String(c)))),
    columnStyles: { 0: { cellWidth: 40, fontStyle: "bold" } },
  });
  return (doc as any).lastAutoTable.finalY + 6;
}

export function addSectionTable(doc: jsPDF, y: number, section: SectionTable): number {
  if (section.title) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(...TEXT_DARK);
    doc.text(section.title, 14, y);
    y += 2;
  }
  autoTable(doc, {
    startY: y + 2,
    theme: "striped",
    headStyles: { fillColor: HEADER_BG, textColor: HEADER_FG },
    head: section.head ? [section.head] : undefined,
    body: section.body.map((r) => r.map((c) => (c == null ? "—" : String(c)))),
    styles: { fontSize: 9, cellPadding: 2 },
    columnStyles: section.columnStyles,
  });
  return (doc as any).lastAutoTable.finalY + 6;
}

export function addParagraph(doc: jsPDF, y: number, title: string, body: string): number {
  if (!body || !body.trim()) return y;
  const W = doc.internal.pageSize.getWidth();
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...TEXT_DARK);
  doc.text(title, 14, y);
  y += 5;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  const lines = doc.splitTextToSize(body, W - 28);
  doc.text(lines, 14, y);
  y += lines.length * 5 + 4;
  return y;
}

/**
 * Adds a centered muted footer line on the current page and saves the file.
 */
export function finalizeAyuzeePdf(doc: jsPDF, fileName: string, footerNote?: string) {
  const W = doc.internal.pageSize.getWidth();
  const ph = doc.internal.pageSize.getHeight();
  const total = (doc as any).internal.getNumberOfPages?.() ?? 1;
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text(
      `${footerNote || "Generated by Ayuzee"} · ${new Date().toLocaleString()}`,
      W / 2,
      ph - 8,
      { align: "center" },
    );
  }
  doc.save(fileName);
}

export function safeFileName(name?: string) {
  return (name || "report").replace(/[^a-zA-Z0-9]+/g, "_").replace(/^_+|_+$/g, "");
}
