import { Button } from "@/components/ui/button";
import { Leaf } from "lucide-react";
import { Link } from "react-router-dom";

const benefits = [
  "🎯 Personalised doctor match",
  "🌿 Daily wellness routine generated by AI",
  "💊 Condition-specific medicine suggestions",
];

const doshas = [
  {
    emoji: "🌬️",
    name: "Vata Constitution",
    elements: "Air + Ether elements · Creative · Energetic · Light",
    prone: "Prone to: Anxiety · Dry skin · Joint pain",
    recommended: "Warm oils · Grounding herbs · Regular sleep",
    className: "-rotate-2 border-info/30 bg-info/10",
  },
  {
    emoji: "🔥",
    name: "Pitta Constitution",
    elements: "Fire + Water elements · Sharp · Ambitious · Intense",
    prone: "Prone to: Inflammation · Acidity · Hair loss",
    recommended: "Cooling foods · Brahmi · Avoid spicy",
    className: "z-10 border-secondary/30 bg-secondary/10 shadow-elegant",
  },
  {
    emoji: "🌊",
    name: "Kapha Constitution",
    elements: "Water + Earth elements · Steady · Loving · Patient",
    prone: "Prone to: Weight gain · Congestion · Lethargy",
    recommended: "Light foods · Stimulating herbs · Exercise",
    className: "rotate-2 border-primary/30 bg-primary/10",
  },
];

const leaves = [
  "left-[6%] top-10 h-10 w-10 rotate-12",
  "left-[18%] bottom-12 h-7 w-7 -rotate-45",
  "right-[8%] top-14 h-12 w-12 -rotate-12",
  "right-[22%] bottom-16 h-8 w-8 rotate-45",
  "left-1/2 top-1/3 h-6 w-6 rotate-90",
  "right-1/3 top-8 h-9 w-9 -rotate-45",
];

export const PrakritiSection = () => (
  <section className="gradient-soft relative overflow-hidden py-20">
    {leaves.map((className) => (
      <Leaf key={className} className={`pointer-events-none absolute text-primary opacity-5 ${className}`} />
    ))}

    <div className="container relative grid items-center gap-12 md:grid-cols-2">
      <div>
        <span className="rounded-full border border-primary/20 bg-accent px-4 py-1.5 text-xs font-semibold text-primary">
          🧬 Ayurvedic AI Diagnosis
        </span>
        <h2 className="mt-4 font-display text-3xl leading-tight md:text-5xl">
          Discover your Dosha. Unlock your health.
        </h2>
        <p className="mt-4 text-lg leading-8 text-muted-foreground">
          Our 5-minute Prakriti quiz analyses 20+ factors to reveal your unique Ayurvedic body constitution — Vata, Pitta, or Kapha. Then we personalise your doctor recommendations, daily routine, and medicine choices.
        </p>

        <div className="mt-6 flex flex-col gap-3">
          {benefits.map((benefit) => (
            <div key={benefit} className="border-l-4 border-primary pl-3 text-sm font-medium text-foreground">
              {benefit}
            </div>
          ))}
        </div>

        <div className="mt-8">
          <Button variant="hero" size="lg" asChild>
            <Link to="/diagnosis/prakriti">Take the Prakriti Quiz — Free, 5 min</Link>
          </Button>
          <p className="mt-2 text-sm text-muted-foreground">✓ No registration required to start</p>
        </div>
      </div>

      <div className="mx-auto w-full max-w-lg">
        <div className="space-y-[-18px]">
          {doshas.map((dosha) => (
            <article key={dosha.name} className={`relative rounded-2xl border bg-card p-5 transition-smooth hover:rotate-0 hover:scale-[1.02] ${dosha.className}`}>
              <div className="flex items-start gap-4">
                <div className="text-4xl" aria-hidden="true">{dosha.emoji}</div>
                <div>
                  <h3 className="text-xl font-semibold text-foreground">{dosha.name}</h3>
                  <p className="mt-1 text-sm text-muted-foreground">{dosha.elements}</p>
                </div>
              </div>
              <div className="mt-4 space-y-2 text-sm">
                <p className="rounded-lg border border-border bg-background/70 px-3 py-2 text-muted-foreground">{dosha.prone}</p>
                <p className="rounded-lg border border-primary/20 bg-primary/5 px-3 py-2 font-medium text-primary">{dosha.recommended}</p>
              </div>
            </article>
          ))}
        </div>
        <p className="mt-8 text-center text-sm italic text-muted-foreground">→ Your result shows which applies to you</p>
      </div>
    </div>
  </section>
);
