-- Emotional Remedy Engine: themes → remedies mapping
CREATE TABLE public.homeo_emotional_themes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  emotional_theme TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  short_description TEXT NOT NULL DEFAULT '',
  trigger_patterns TEXT[] NOT NULL DEFAULT '{}',
  dominant_reaction TEXT[] NOT NULL DEFAULT '{}',
  body_correlations TEXT[] NOT NULL DEFAULT '{}',
  likely_remedies_ranked JSONB NOT NULL DEFAULT '[]'::jsonb,
  differential_remedies TEXT[] NOT NULL DEFAULT '{}',
  followup_questions TEXT[] NOT NULL DEFAULT '{}',
  caution_notes TEXT NOT NULL DEFAULT '',
  doctor_notes TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_homeo_emotional_themes_sort ON public.homeo_emotional_themes(sort_order);
CREATE INDEX idx_homeo_emotional_themes_active ON public.homeo_emotional_themes(is_active);
CREATE INDEX idx_homeo_emotional_themes_theme_trgm ON public.homeo_emotional_themes USING gin (emotional_theme gin_trgm_ops);

ALTER TABLE public.homeo_emotional_themes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated can view active emotional themes"
  ON public.homeo_emotional_themes FOR SELECT
  TO authenticated
  USING (is_active = true OR public.is_admin_or_super(auth.uid()));

CREATE POLICY "Admins manage emotional themes - insert"
  ON public.homeo_emotional_themes FOR INSERT
  TO authenticated
  WITH CHECK (public.is_admin_or_super(auth.uid()));

CREATE POLICY "Admins manage emotional themes - update"
  ON public.homeo_emotional_themes FOR UPDATE
  TO authenticated
  USING (public.is_admin_or_super(auth.uid()))
  WITH CHECK (public.is_admin_or_super(auth.uid()));

CREATE POLICY "Admins manage emotional themes - delete"
  ON public.homeo_emotional_themes FOR DELETE
  TO authenticated
  USING (public.is_admin_or_super(auth.uid()));

CREATE TRIGGER update_homeo_emotional_themes_updated_at
  BEFORE UPDATE ON public.homeo_emotional_themes
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Seed: 50 themes
INSERT INTO public.homeo_emotional_themes
  (emotional_theme, slug, short_description, trigger_patterns, dominant_reaction, body_correlations, likely_remedies_ranked, differential_remedies, followup_questions, caution_notes, sort_order)
VALUES
('Humiliation','humiliation','Feels insulted, disrespected, wounded dignity.',ARRAY['scolding','criticism','public insult','domination'],ARRAY['suppressed anger','silent hurt','trembling after insult'],ARRAY['headache','gastritis','pelvic tension','sleep disturbance'],'[{"remedy":"Staphysagria","score":95},{"remedy":"Colocynthis","score":70},{"remedy":"Ignatia","score":65}]'::jsonb,ARRAY['Natrum Mur','Nux Vomica'],ARRAY['Do you express anger or suppress it?','Do you replay the insult mentally?'],'Differentiate from grief and rage states.',1),
('Rejection','rejection','Wound from being unwanted, unloved, or pushed away.',ARRAY['abandonment','breakup','parental neglect'],ARRAY['silent withdrawal','closed heart','weeping alone'],ARRAY['palpitations','headache','appetite loss'],'[{"remedy":"Natrum Muriaticum","score":92},{"remedy":"Ignatia","score":80},{"remedy":"Pulsatilla","score":68}]'::jsonb,ARRAY['Aurum Met','Sepia'],ARRAY['Do you cry when alone?','Do you avoid sympathy?'],'Distinguish craving company (Pulsatilla) vs aversion (Natrum Mur).',2),
('Silent Grief','silent-grief','Internalised sorrow not openly expressed.',ARRAY['loss','death of loved one','disappointed love'],ARRAY['sighing','suppressed weeping','closed-off'],ARRAY['lump in throat','insomnia','tightness in chest'],'[{"remedy":"Natrum Muriaticum","score":94},{"remedy":"Ignatia","score":88},{"remedy":"Phosphoric Acid","score":72}]'::jsonb,ARRAY['Aurum Met','Causticum'],ARRAY['Do you sigh often?','Do you avoid speaking of the loss?'],'Phos Acid for grief leading to apathy/exhaustion.',3),
('Betrayal','betrayal','Trust broken by close person; lasting wound.',ARRAY['infidelity','friend turning hostile','broken promises'],ARRAY['suspicion','simmering rage','cynical detachment'],ARRAY['throat constriction','palpitations','insomnia'],'[{"remedy":"Lachesis","score":90},{"remedy":"Natrum Muriaticum","score":78},{"remedy":"Staphysagria","score":72}]'::jsonb,ARRAY['Anacardium','Aurum Met'],ARRAY['Do you feel suspicious now of others?','Has it changed how you trust?'],'Lachesis: loquacious + jealous; Nat Mur: silent grief.',4),
('Jealousy','jealousy','Possessive insecurity, envy, suspicion.',ARRAY['partner attention to others','sibling rivalry'],ARRAY['interrogation','clinging','accusation'],ARRAY['flushes','headache','throat sensitivity'],'[{"remedy":"Lachesis","score":92},{"remedy":"Hyoscyamus","score":78},{"remedy":"Nux Vomica","score":65}]'::jsonb,ARRAY['Apis','Pulsatilla'],ARRAY['Do you check on partner constantly?','Do you feel rage or sadness?'],'Hyoscyamus: erotic suspicion; Lachesis: possessive.',5),
('Anticipatory Fear','anticipatory-fear','Anxiety before events; dread of future moment.',ARRAY['exam','interview','public event'],ARRAY['restlessness','diarrhoea','cannot sleep night before'],ARRAY['loose stools','trembling','dry mouth'],'[{"remedy":"Gelsemium","score":94},{"remedy":"Argentum Nitricum","score":88},{"remedy":"Aconite","score":70}]'::jsonb,ARRAY['Lycopodium','Silicea'],ARRAY['Do you have diarrhoea before events?','Do you tremble?'],'Gels: dullness + heaviness; Arg Nit: hurried + impulsive.',6),
('Panic / Sudden Fear','panic-sudden-fear','Acute terror, abrupt onset.',ARRAY['shock','accident','sudden bad news'],ARRAY['screaming','frozen','wants to flee'],ARRAY['palpitations','dyspnoea','cold sweat'],'[{"remedy":"Aconite","score":95},{"remedy":"Arsenicum Album","score":75},{"remedy":"Gelsemium","score":60}]'::jsonb,ARRAY['Stramonium','Opium'],ARRAY['Was the onset sudden?','Predicts time of death?'],'Aconite: acute, sudden; Ars Alb: anxious + restless at night.',7),
('Fear of Death','fear-of-death','Conviction of impending death.',ARRAY['illness','panic episode','cardiac symptom'],ARRAY['anxiety','seeking help','restless'],ARRAY['palpitations','chest tightness','cold extremities'],'[{"remedy":"Aconite","score":92},{"remedy":"Arsenicum Album","score":88},{"remedy":"Phosphorus","score":70}]'::jsonb,ARRAY['Lachesis','Calcarea Carb'],ARRAY['Do you predict your own death?','Worse at night?'],'Rule out cardiac aetiology before remedy.',8),
('Fear of Failure','fear-of-failure','Dread of inadequacy, of being exposed.',ARRAY['promotion','exam','responsibility'],ARRAY['avoidance','overpreparation','anxiety dreams'],ARRAY['IBS','headache','insomnia'],'[{"remedy":"Lycopodium","score":92},{"remedy":"Argentum Nitricum","score":80},{"remedy":"Gelsemium","score":72}]'::jsonb,ARRAY['Silicea','Anacardium'],ARRAY['Do you feel a fraud?','Avoid challenges?'],'Lyc: cowardly inwardly, bold outwardly.',9),
('Performance Anxiety','performance-anxiety','Fear of failing in front of others.',ARRAY['public speaking','stage','audition','viva'],ARRAY['trembling','sweat','memory blank'],ARRAY['diarrhoea','palpitations','dry mouth'],'[{"remedy":"Argentum Nitricum","score":94},{"remedy":"Gelsemium","score":90},{"remedy":"Lycopodium","score":82}]'::jsonb,ARRAY['Silicea','Ambra Grisea'],ARRAY['Do you forget words?','Loose stools before stage?'],'Combine with breathwork as adjunct.',10),
('Suppressed Anger','suppressed-anger','Anger held in, never expressed.',ARRAY['authority','injustice','workplace abuse'],ARRAY['silent fuming','overcompliance','psychosomatic'],ARRAY['gastritis','BP rise','PMS'],'[{"remedy":"Staphysagria","score":94},{"remedy":"Nux Vomica","score":78},{"remedy":"Ignatia","score":68}]'::jsonb,ARRAY['Lycopodium','Natrum Mur'],ARRAY['Do you bottle anger?','Do you cry instead?'],'Staph: classical suppressed indignation.',11),
('Explosive Anger','explosive-anger','Sudden outbursts, violent reaction.',ARRAY['contradiction','frustration','hunger'],ARRAY['shouting','throwing','striking'],ARRAY['flushed face','headache','palpitations'],'[{"remedy":"Nux Vomica","score":92},{"remedy":"Chamomilla","score":80},{"remedy":"Belladonna","score":70}]'::jsonb,ARRAY['Hepar Sulph','Stramonium'],ARRAY['Trigger trivial?','Regret afterwards?'],'Belladonna: red, hot, sudden.',12),
('Irritability from Pain','irritability-from-pain','Unbearable irritability when in pain.',ARRAY['toothache','colic','injury'],ARRAY['snapping','intolerant of touch','demands relief'],ARRAY['toothache','colic','neuralgia'],'[{"remedy":"Chamomilla","score":94},{"remedy":"Nux Vomica","score":80},{"remedy":"Coffea","score":72}]'::jsonb,ARRAY['Hepar Sulph','Magnesia Phos'],ARRAY['Cannot bear the pain?','Better by carrying (children)?'],'Chamomilla classic in children + dentition.',13),
('Oversensitivity','oversensitivity','Hypersensitive to noise, light, touch, emotion.',ARRAY['loud noises','rough handling','criticism'],ARRAY['startles','weeps','irritated easily'],ARRAY['headache','insomnia','jumpiness'],'[{"remedy":"Chamomilla","score":85},{"remedy":"Coffea","score":82},{"remedy":"Nux Vomica","score":78}]'::jsonb,ARRAY['Phosphorus','Nitric Acid'],ARRAY['Sensitive to noise?','Sensitive to music or smells?'],'Coffea: oversensitive after good news too.',14),
('Control Freak Tendencies','control-freak','Need to control environment and people.',ARRAY['disorder','dependence on others','uncertainty'],ARRAY['micromanaging','irritability','rigidity'],ARRAY['BP rise','tension headache','GERD'],'[{"remedy":"Nux Vomica","score":88},{"remedy":"Arsenicum Album","score":86},{"remedy":"Lycopodium","score":76}]'::jsonb,ARRAY['Carcinosin','Calcarea Fluor'],ARRAY['Cannot delegate?','Anxious if disorder around you?'],'Ars Alb: control to manage anxiety; Nux: control from ambition.',15),
('Perfectionism','perfectionism','Cannot tolerate flaws; fastidious.',ARRAY['untidy environment','imperfect work'],ARRAY['rechecking','rewriting','self-criticism'],ARRAY['tension','insomnia','GI symptoms'],'[{"remedy":"Arsenicum Album","score":94},{"remedy":"Nux Vomica","score":78},{"remedy":"Carcinosin","score":76}]'::jsonb,ARRAY['Silicea','Anacardium'],ARRAY['Things must be just so?','You redo work others did?'],'Carcinosin: perfectionism + need to please.',16),
('Anxiety About Health','health-anxiety','Hypochondriacal fear, scanning body.',ARRAY['mild symptom','medical news','reading symptoms'],ARRAY['Googling','seeking reassurance','restless'],ARRAY['palpitations','dizziness','GI'],'[{"remedy":"Arsenicum Album","score":94},{"remedy":"Aconite","score":70},{"remedy":"Calcarea Carb","score":68}]'::jsonb,ARRAY['Phosphorus','Kali Carb'],ARRAY['Do you check pulse often?','Worse at night/alone?'],'Ars Alb: anxious + restless 1–3 am.',17),
('Security Anxiety','security-anxiety','Fear of losing safety, money, support.',ARRAY['financial stress','job insecurity'],ARRAY['hoarding','overplanning','clinging'],ARRAY['fatigue','sweating','cold extremities'],'[{"remedy":"Calcarea Carbonica","score":92},{"remedy":"Arsenicum Album","score":78},{"remedy":"Kali Carbonicum","score":72}]'::jsonb,ARRAY['Bryonia','Lycopodium'],ARRAY['Do you fear poverty?','Need fixed routine?'],'Calc Carb: needs security + routine.',18),
('Loneliness','loneliness','Persistent felt sense of being alone.',ARRAY['relocation','widowhood','social withdrawal'],ARRAY['weeps alone','romanticises past','isolates'],ARRAY['insomnia','appetite changes','low energy'],'[{"remedy":"Natrum Muriaticum","score":88},{"remedy":"Phosphorus","score":80},{"remedy":"Pulsatilla","score":76}]'::jsonb,ARRAY['Aurum Met','Sepia'],ARRAY['Better or worse with company?'],'Phos: better with company; Nat Mur: prefers solitude.',19),
('Need for Company','need-for-company','Cannot bear being alone.',ARRAY['being alone','silence','dark'],ARRAY['calls people','fearful when alone'],ARRAY['palpitations','restlessness'],'[{"remedy":"Pulsatilla","score":94},{"remedy":"Phosphorus","score":88},{"remedy":"Arsenicum Album","score":80}]'::jsonb,ARRAY['Lycopodium','Stramonium'],ARRAY['Anxious if no one home?'],'Ars: company in next room enough.',20),
('Need for Appreciation','need-for-appreciation','Strong craving for recognition.',ARRAY['lack of praise','being overlooked'],ARRAY['boasting','overworking','sulking'],ARRAY['fatigue','headache'],'[{"remedy":"Lycopodium","score":88},{"remedy":"Aurum Metallicum","score":80},{"remedy":"Pulsatilla","score":72}]'::jsonb,ARRAY['Platina','Palladium'],ARRAY['Hurt if not noticed?','Compete for praise?'],'Aurum: collapses if appreciation absent.',21),
('Inferiority','inferiority','Persistent sense of being lesser.',ARRAY['comparison','high achievers around'],ARRAY['avoidance','self-deprecation'],ARRAY['fatigue','psychosomatic'],'[{"remedy":"Lycopodium","score":90},{"remedy":"Silicea","score":82},{"remedy":"Baryta Carbonica","score":74}]'::jsonb,ARRAY['Anacardium','Thuja'],ARRAY['Feel small in groups?'],'Baryta Carb: childlike inferiority.',22),
('Lack of Confidence','lack-of-confidence','Cannot trust own ability.',ARRAY['public speaking','new responsibility'],ARRAY['hesitation','procrastination'],ARRAY['weakness','tremor'],'[{"remedy":"Gelsemium","score":88},{"remedy":"Lycopodium","score":86},{"remedy":"Silicea","score":80}]'::jsonb,ARRAY['Anacardium','Argentum Nitricum'],ARRAY['Avoid challenges?'],'Silicea: yielding outwardly, firm core.',23),
('Stage Fright','stage-fright','Acute fear of being seen performing.',ARRAY['stage','camera','viva'],ARRAY['blank mind','tremor','sweat'],ARRAY['palpitations','diarrhoea'],'[{"remedy":"Gelsemium","score":94},{"remedy":"Argentum Nitricum","score":90},{"remedy":"Lycopodium","score":80}]'::jsonb,ARRAY['Silicea','Ambra Grisea'],ARRAY['Forget words on stage?'],'Combine with rehearsal therapy.',24),
('Shame','shame','Sense of being bad/exposed.',ARRAY['mistake exposed','sexual shame'],ARRAY['hiding','blushing','withdrawal'],ARRAY['flushes','GI','insomnia'],'[{"remedy":"Staphysagria","score":88},{"remedy":"Natrum Muriaticum","score":82},{"remedy":"Ignatia","score":72}]'::jsonb,ARRAY['Aurum Met','Carcinosin'],ARRAY['Replay the moment mentally?'],'Address with care; trauma-informed.',25),
('Guilt','guilt','Persistent self-blame for harm done/imagined.',ARRAY['religious','past actions','loss'],ARRAY['ruminations','self-punishment'],ARRAY['insomnia','depression'],'[{"remedy":"Aurum Metallicum","score":90},{"remedy":"Natrum Sulphuricum","score":78},{"remedy":"Ignatia","score":72}]'::jsonb,ARRAY['Cyclamen','Veratrum Album'],ARRAY['Feel responsible for loss?'],'Aurum: severe guilt + suicidal ideation — refer.',26),
('Self-Criticism','self-criticism','Inner harsh judge.',ARRAY['mistake','low performance'],ARRAY['rumination','anhedonia'],ARRAY['fatigue','sleep disturbance'],'[{"remedy":"Aurum Metallicum","score":86},{"remedy":"Arsenicum Album","score":80},{"remedy":"Natrum Muriaticum","score":76}]'::jsonb,ARRAY['Carcinosin','Anacardium'],ARRAY['Speak harshly to yourself?'],'Combine with CBT-style adjunct.',27),
('Depression after Loss','depression-after-loss','Sustained low mood after grief.',ARRAY['death','separation','job loss'],ARRAY['anhedonia','isolation','tearfulness'],ARRAY['weight loss','insomnia'],'[{"remedy":"Ignatia","score":92},{"remedy":"Natrum Muriaticum","score":88},{"remedy":"Phosphoric Acid","score":80}]'::jsonb,ARRAY['Aurum Met','Causticum'],ARRAY['Onset traceable to loss?'],'Screen for suicidality; refer if positive.',28),
('Emotional Numbness','emotional-numbness','Cannot feel; flat affect.',ARRAY['chronic stress','prolonged grief'],ARRAY['detachment','indifference'],ARRAY['fatigue','low libido'],'[{"remedy":"Phosphoric Acid","score":90},{"remedy":"Sepia","score":82},{"remedy":"Natrum Muriaticum","score":74}]'::jsonb,ARRAY['Opium','Carcinosin'],ARRAY['Indifferent to loved ones?'],'Sepia: indifference + irritability.',29),
('Burnout','burnout','Physical + mental exhaustion from prolonged work.',ARRAY['overwork','caregiving','no recovery'],ARRAY['cynicism','exhaustion','irritability'],ARRAY['fatigue','headache','GI'],'[{"remedy":"Nux Vomica","score":88},{"remedy":"Kali Phosphoricum","score":86},{"remedy":"Phosphoric Acid","score":80}]'::jsonb,ARRAY['Picric Acid','Cocculus'],ARRAY['Wired but tired?'],'Picric Acid: study burnout.',30),
('Work Stress','work-stress','Pressure from deadlines, expectation.',ARRAY['deadlines','meetings','overload'],ARRAY['hurried','irritated','sleepless'],ARRAY['acidity','tension headache'],'[{"remedy":"Nux Vomica","score":92},{"remedy":"Kali Phosphoricum","score":80},{"remedy":"Argentum Nitricum","score":74}]'::jsonb,ARRAY['Coffea','Lycopodium'],ARRAY['Worse on Mondays?'],'Address sleep + stimulant use.',31),
('Hurry / Rush Mentality','hurry-mentality','Sense time always short; impulsive speed.',ARRAY['time pressure','queues'],ARRAY['talks fast','walks fast','impulsive'],ARRAY['palpitations','GI rush'],'[{"remedy":"Argentum Nitricum","score":92},{"remedy":"Nux Vomica","score":80},{"remedy":"Sulphur","score":68}]'::jsonb,ARRAY['Lilium Tigrinum','Tarentula'],ARRAY['Do you hurry even when not late?'],'Arg Nit: + anxiety, sweets craving.',32),
('Impatience','impatience','Cannot wait, snaps quickly.',ARRAY['delays','slowness'],ARRAY['snapping','tapping','interrupting'],ARRAY['BP rise','headache'],'[{"remedy":"Nux Vomica","score":90},{"remedy":"Chamomilla","score":80},{"remedy":"Sulphur","score":70}]'::jsonb,ARRAY['Argentum Nitricum','Tarentula'],ARRAY['Honk in traffic instantly?'],'Often comorbid with hurry mentality.',33),
('Suspicion','suspicion','Mistrust of others'' motives.',ARRAY['betrayal','workplace politics'],ARRAY['guarded','interrogating','isolating'],ARRAY['insomnia','BP'],'[{"remedy":"Lachesis","score":90},{"remedy":"Hyoscyamus","score":80},{"remedy":"Anacardium","score":74}]'::jsonb,ARRAY['Mercurius','Stramonium'],ARRAY['Suspect partner?','Suspect colleagues?'],'Anacardium: split mind + suspicion.',34),
('Split Mind / Indecision','split-mind','Feels two wills inside; cannot choose.',ARRAY['ethical dilemma','important decision'],ARRAY['paralysis','flip-flopping'],ARRAY['headache','insomnia'],'[{"remedy":"Anacardium","score":92},{"remedy":"Lycopodium","score":78},{"remedy":"Pulsatilla","score":70}]'::jsonb,ARRAY['Baryta Carb','Kali Sulph'],ARRAY['Two voices inside?'],'Anacardium classical "angel and devil".',35),
('Memory Weakness from Stress','memory-weakness-stress','Forgetfulness due to overload.',ARRAY['exam','overwork','grief'],ARRAY['blank moments','word-finding loss'],ARRAY['fatigue','headache'],'[{"remedy":"Kali Phosphoricum","score":88},{"remedy":"Anacardium","score":78},{"remedy":"Lycopodium","score":72}]'::jsonb,ARRAY['Phosphoric Acid','Baryta Carb'],ARRAY['Worse near exams?'],'Rule out organic causes.',36),
('Emotional Dependency','emotional-dependency','Cannot function without close other.',ARRAY['relationship','family'],ARRAY['clinging','seeking reassurance'],ARRAY['palpitations','insomnia'],'[{"remedy":"Pulsatilla","score":92},{"remedy":"Phosphorus","score":80},{"remedy":"Sepia","score":60}]'::jsonb,ARRAY['Calcarea Carb','Bismuth'],ARRAY['Cannot be alone for long?'],'Pulsatilla: yielding, weepy.',37),
('Aversion to Family','aversion-to-family','Wants distance from family/loved ones.',ARRAY['hormonal change','postpartum','menopause'],ARRAY['indifference','irritability'],ARRAY['fatigue','low libido','PMS'],'[{"remedy":"Sepia","score":94},{"remedy":"Natrum Muriaticum","score":78},{"remedy":"Sulphur","score":68}]'::jsonb,ARRAY['Lilium Tigrinum','Platina'],ARRAY['Indifferent to children/spouse?'],'Sepia: classical hormonal aversion.',38),
('Hormonal Irritability','hormonal-irritability','Mood swings tied to cycle/menopause.',ARRAY['premenstrual','perimenopause'],ARRAY['snapping','weeping','flushes'],ARRAY['PMS','hot flushes','headache'],'[{"remedy":"Sepia","score":90},{"remedy":"Lachesis","score":86},{"remedy":"Pulsatilla","score":76}]'::jsonb,ARRAY['Cimicifuga','Folliculinum'],ARRAY['Worse before menses?'],'Lachesis: better when flow starts.',39),
('Weeping Easily','weeping-easily','Tears at the slightest cause.',ARRAY['kindness','music','memory'],ARRAY['tearful','seeks consolation'],ARRAY['headache after weeping'],'[{"remedy":"Pulsatilla","score":94},{"remedy":"Ignatia","score":80},{"remedy":"Natrum Muriaticum","score":68}]'::jsonb,ARRAY['Phosphorus','Sepia'],ARRAY['Better after weeping?'],'Nat Mur: weeps alone, worse from sympathy.',40),
('Consolation Aggravates','consolation-aggravates','Worse from sympathy.',ARRAY['well-meaning relatives','public sympathy'],ARRAY['irritation','withdrawal'],ARRAY['headache','insomnia'],'[{"remedy":"Natrum Muriaticum","score":94},{"remedy":"Sepia","score":82},{"remedy":"Ignatia","score":72}]'::jsonb,ARRAY['Silicea','Calcarea Phos'],ARRAY['Hate being asked "are you ok"?'],'Strong differentiating modality.',41),
('Consolation Ameliorates','consolation-ameliorates','Better from sympathy.',ARRAY['stress','illness'],ARRAY['seeks hugs','calls family'],ARRAY['palpitations'],'[{"remedy":"Pulsatilla","score":92},{"remedy":"Phosphorus","score":86}]'::jsonb,ARRAY['Phosphoric Acid','Cyclamen'],ARRAY['Better when held?'],'Often warm-blooded, weepy.',42),
('Fear in Darkness','fear-in-darkness','Acute fear when lights are off.',ARRAY['darkness','being alone at night'],ARRAY['screams','clings','imagines monsters'],ARRAY['insomnia','night terrors'],'[{"remedy":"Stramonium","score":94},{"remedy":"Aconite","score":78},{"remedy":"Phosphorus","score":72}]'::jsonb,ARRAY['Calcarea Carb','Causticum'],ARRAY['Sees figures in dark?'],'Stramonium: paediatric night terrors.',43),
('Night Anxiety','night-anxiety','Anxiety worst between midnight and 3 am.',ARRAY['darkness','silence','illness'],ARRAY['restlessness','pacing'],ARRAY['palpitations','sweating'],'[{"remedy":"Arsenicum Album","score":94},{"remedy":"Aconite","score":72},{"remedy":"Kali Carbonicum","score":68}]'::jsonb,ARRAY['Causticum','Phosphorus'],ARRAY['Wakes 1–3 am anxious?'],'Ars Alb time modality is key.',44),
('Restlessness','restlessness','Cannot be still; must move.',ARRAY['anxiety','pain','illness'],ARRAY['pacing','changing position'],ARRAY['cold','pain','fatigue'],'[{"remedy":"Arsenicum Album","score":92},{"remedy":"Rhus Toxicodendron","score":86},{"remedy":"Aconite","score":72}]'::jsonb,ARRAY['Tarentula','Zincum'],ARRAY['Better moving?'],'Rhus Tox: physical restlessness from joint pain.',45),
('Hyperactivity Child','hyperactivity-child','Cannot sit still; impulsive.',ARRAY['school','overstimulation'],ARRAY['running','climbing','impulsive'],ARRAY['sleep issues','appetite swings'],'[{"remedy":"Tarentula Hispanica","score":92},{"remedy":"Chamomilla","score":74},{"remedy":"Cina","score":70}]'::jsonb,ARRAY['Stramonium','Hyoscyamus'],ARRAY['Better with music?'],'Tarentula: sensitive to music/rhythm.',46),
('Irritable Child','irritable-child','Cross, demands, throws things.',ARRAY['dentition','hunger','overstimulation'],ARRAY['screams','strikes','demands'],ARRAY['colic','dentition pain'],'[{"remedy":"Chamomilla","score":94},{"remedy":"Cina","score":80},{"remedy":"Belladonna","score":72}]'::jsonb,ARRAY['Antimonium Crud','Nux Vomica'],ARRAY['Better being carried?'],'Chamomilla classic teething child.',47),
('Neglected Feeling','neglected-feeling','Sense of being unloved/forgotten.',ARRAY['parental absence','sibling preference'],ARRAY['weeping','withdrawal','seeking attention'],ARRAY['appetite changes','psychosomatic'],'[{"remedy":"Natrum Muriaticum","score":88},{"remedy":"Pulsatilla","score":82},{"remedy":"Sepia","score":68}]'::jsonb,ARRAY['Magnesia Carb','Carcinosin'],ARRAY['Felt unloved as child?'],'Mag Carb: orphan-like feeling.',48),
('Competitive Aggression','competitive-aggression','Driven, must win, ruthless.',ARRAY['career','sport','rivalry'],ARRAY['dominance','impatience','snapping'],ARRAY['BP','GERD','insomnia'],'[{"remedy":"Nux Vomica","score":90},{"remedy":"Lycopodium","score":80},{"remedy":"Lachesis","score":72}]'::jsonb,ARRAY['Anacardium','Causticum'],ARRAY['Hate to lose at anything?'],'Nux: type-A executive picture.',49),
('Loss of Purpose','loss-of-purpose','Existential void; no meaning.',ARRAY['retirement','loss','spiritual crisis'],ARRAY['apathy','withdrawal','low mood'],ARRAY['fatigue','insomnia','low libido'],'[{"remedy":"Aurum Metallicum","score":92},{"remedy":"Sepia","score":78},{"remedy":"Phosphoric Acid","score":74}]'::jsonb,ARRAY['Causticum','Ignatia'],ARRAY['Life feels meaningless?'],'Aurum: screen for suicidality — refer.',50);