WITH female AS (SELECT id FROM treatment_systems WHERE slug='female-health-issues'),
     ncd AS (SELECT id FROM treatment_systems WHERE slug='lifestyle-disorders')
INSERT INTO public.health_conditions (
  slug, name, tagline, hero_title, hero_subtitle,
  is_published, sort_order, system_id,
  consult_banner_text, content_sections, related_medicines, faqs
) VALUES
(
  'leucorrhoea', 'Leucorrhoea (White Discharge)',
  'Ayurvedic care for abnormal vaginal discharge.',
  'Leucorrhoea — Causes, Symptoms & Ayurvedic Remedies',
  'Restore reproductive health, clear infection, and rebuild strength with classical Ayurveda.',
  true, 24, (SELECT id FROM female),
  'Talk to an Ayurveda Doctor',
  '[
    {"key":"overview","title":"Overview","body_markdown":"Leucorrhoea, also known as **vaginal discharge**, is a common condition affecting women — characterised by the secretion of a whitish or yellowish fluid from the vagina. The discharge itself is normal in small amounts and plays a role in maintaining vaginal health by clearing dead cells and bacteria.\n\nHowever, when discharge becomes excessive, foul-smelling, thick or coloured, it may indicate an underlying imbalance or infection. Ayurveda calls this ***Shweta Pradara*** and treats it as a vitiation of **Kapha dosha** with weakness of *rasa dhatu* (nutritive tissue)."},
    {"key":"causes","title":"Causes","body_markdown":"### A. Ayurvedic Causes\n- **Kapha imbalance** — excessive Kapha due to a heavy, oily, sweet diet produces a thick, mucousy discharge.\n- **Aggravated Vata + Pitta** — produces dryness or burning along with discharge.\n- **Weak digestive fire (mandagni)** — leads to *ama* (toxin) accumulation in *artava srotas*.\n\n### B. Modern Causes\n- **Infections** — bacterial, fungal (Candida), trichomonas, chlamydia.\n- **Poor hygiene** — improper cleaning, scented soaps, prolonged use of synthetic innerwear.\n- **Sexually Transmitted Infections (STIs)** — gonorrhoea, chlamydia, trichomoniasis.\n- **Hormonal changes** — pregnancy, menopause, contraceptives.\n- **Diabetes / weak immunity** — increases yeast infections.\n- **Stress and fatigue** — disturbs hormonal balance."},
    {"key":"symptoms","title":"Symptoms","body_markdown":"### General Symptoms\n- Excessive vaginal discharge — white, yellowish, green or grey\n- Foul odour\n- Itching, irritation, burning around the vulva\n- Lower-abdominal pain or low-back pain\n- Pain during intercourse\n- Fatigue, weakness, irritability\n- Burning urination if infection is present\n- Spotting between periods in chronic cases\n\n### Ayurvedic View — Dosha-wise\n- **Kapha-type** — thick, white, mucousy, painless discharge.\n- **Pitta-type** — yellow/greenish discharge with burning and inflammation.\n- **Vata-type** — scanty, frothy, brownish discharge with dryness and pain."},
    {"key":"remedies","title":"Ayurvedic Remedies","body_markdown":"### A. Home Remedies\n- **Coconut water** — cools Pitta, hydrates and balances vaginal flora.\n- **Banana + cumin** — a classical remedy; reduces Kapha discharge.\n- **Fenugreek seed water** — overnight soak, drink in the morning.\n- **Amla juice with honey** — boosts immunity and reduces discharge.\n- **Triphala kashaya wash** — antimicrobial sitz-bath (under doctor advice).\n\n### B. Classical Herbs\n- **Ashoka** *(Saraca indica)* — uterine tonic, controls discharge.\n- **Lodhra** — astringent, reduces white discharge.\n- **Shatavari** — restores reproductive strength.\n- **Triphala + Guduchi** — detoxifies and supports immunity.\n- **Pushyanuga Churna** — gold-standard formulation for *shweta pradara*.\n- **Chandanasava, Asokarishta** — classical liquids for chronic cases.\n\n### C. Lifestyle\n- Wear cotton, breathable innerwear; avoid tight synthetics.\n- Maintain hygiene; avoid scented washes and douches.\n- Reduce sugar, dairy, fried and fermented foods (Kapha-aggravating).\n- Practice yoga: *Bhujangasana, Pawanmuktasana, Malasana*.\n- Manage stress; sleep well.\n\n> If discharge is foul-smelling, blood-tinged or with severe pain/fever — consult a gynaecologist immediately to rule out infection or pathology."}
  ]'::jsonb,
  '[
    {"name":"Pushyanuga Churna","price":189,"url":"/shop"},
    {"name":"Vrida Ashokarishta","price":225,"url":"/shop"},
    {"name":"Vrida Lodhra Tablet","price":199,"url":"/shop"}
  ]'::jsonb,
  '[
    {"q":"Is white discharge always abnormal?","a":"No. A small amount of clear or milky white discharge is normal and healthy. Treatment is needed only when it is excessive, foul-smelling, coloured or itchy."},
    {"q":"How long does Ayurvedic treatment for leucorrhoea take?","a":"Most cases improve within 4–6 weeks of consistent treatment. Chronic or infection-related cases may need 2–3 months."}
  ]'::jsonb
),
(
  'diabetes', 'Diabetes (Madhumeha)',
  'Reverse early diabetes and manage blood sugar with classical Ayurveda.',
  'Diabetes — Causes, Symptoms & Ayurvedic Remedies',
  'Improve insulin sensitivity, prevent complications, and rebalance metabolism naturally.',
  true, 30, (SELECT id FROM ncd),
  'Talk to an Ayurveda Doctor',
  '[
    {"key":"overview","title":"Overview","body_markdown":"Diabetes is a chronic metabolic condition in which the body cannot regulate blood sugar (glucose) properly. It primarily occurs when the body either does not produce enough **insulin** or cannot use insulin effectively, leading to high blood sugar levels over time.\n\nThe condition is classified into two main types: **Type 1 diabetes** (autoimmune; insulin-dependent) and **Type 2 diabetes** (insulin-resistance; lifestyle-driven). Ayurveda describes diabetes as ***Madhumeha***, a chronic *Kapha-Medas* disorder belonging to the broader category of ***Prameha*** (urinary disorders).\n\nManaging blood sugar levels, maintaining a healthy diet, regular exercise, and Ayurvedic medicines can help prevent or delay complications such as heart disease, neuropathy, kidney damage and vision loss."},
    {"key":"causes","title":"Causes","body_markdown":"### A. Lifestyle Factors\n- **Sedentary lifestyle** — lack of physical activity reduces insulin sensitivity.\n- **Unhealthy diet** — high intake of sugar, refined carbs, fried food, sweets.\n- **Obesity** — especially abdominal fat increases insulin resistance.\n- **Chronic stress** — disturbs cortisol and insulin metabolism.\n- **Sleep deprivation** — poor sleep affects glucose metabolism and insulin sensitivity.\n\n### B. Genetic & Medical Factors\n- **Family history** — genetic predisposition increases risk.\n- **Hypertension** — closely linked to insulin resistance.\n- **PCOS in women** — high insulin levels and irregular ovulation.\n- **Pancreatic dysfunction** — damage to insulin-producing beta cells.\n- **Gestational diabetes** — long-term risk after diabetes during pregnancy.\n\n### C. Ayurvedic Perspective on Causes\n- **Aggravated Kapha + Medas** — due to sweet, oily, heavy food and lack of exercise.\n- **Weak Agni (digestion)** — produces *ama* (toxins) that block insulin pathways.\n- **Bija dushti** *(seed defect)* — hereditary form of diabetes (genetic).\n- **Vata aggravation** — leads to dryness in the body, causing damage to *dhatus* (tissues)."},
    {"key":"symptoms","title":"Symptoms","body_markdown":"### A. Early Symptoms\n- Frequent urination (polyuria); high sugar passes excess via urine\n- Increased thirst (polydipsia)\n- Unusual hunger even after meals (polyphagia)\n- Unexplained weight loss or weight gain\n- Tiredness, fatigue\n- Slow-healing wounds\n- Blurred vision\n- Recurrent skin or urinary infections\n\n### B. Long-term Symptoms\n- Burning sensation, tingling in hands and feet (diabetic neuropathy)\n- Erectile dysfunction in men, menstrual irregularity in women\n- Numbness or tingling in feet → risk of diabetic foot ulcers\n- Heart disease, stroke, kidney damage in uncontrolled cases\n- Dark patches on skin (acanthosis nigricans)\n\n### C. Severe Complications\n- Diabetic ketoacidosis (Type 1)\n- Hyperosmolar hyperglycaemic state (Type 2)\n- Vision loss (retinopathy)\n- Kidney failure (nephropathy)\n- Repeated infections — UTIs, fungal infections, slow-healing wounds"},
    {"key":"remedies","title":"Ayurvedic Remedies","body_markdown":"### A. Classical Herbs\n- **Vijaysar** *(Pterocarpus marsupium)* — improves insulin sensitivity; traditional ''diabetes wood''.\n- **Jamun seed powder** *(Syzygium cumini)* — reduces blood-sugar spikes.\n- **Gudmar** *(Gymnema sylvestre)* — ''sugar destroyer''; reduces sugar cravings.\n- **Methi (Fenugreek) seeds** — soaked overnight; lowers fasting glucose.\n- **Bitter gourd (Karela) juice** — natural insulin-mimetic.\n- **Neem leaves** — supports pancreatic function.\n- **Triphala + Guduchi** — detoxifies and supports immunity.\n\n### B. Dietary Recommendations\n- Eat a **high-fibre diet** — millets, oats, legumes, and green leafy vegetables.\n- Consume healthy fats — flaxseeds, walnuts, ghee in moderation.\n- Avoid processed and sugary foods, white rice, refined flour, and sweetened drinks.\n- Eat 5 small meals to maintain steady blood-sugar levels.\n- Drink **karela, jamun, amla juice** on an empty stomach.\n\n### C. Lifestyle Modifications\n- **Daily exercise** — brisk walking 45 minutes; yoga improves insulin sensitivity.\n- Yoga: *Surya Namaskar, Mandukasana, Ardha Matsyendrasana, Pranayama*.\n- Stress management — meditation lowers cortisol and helps balance sugar.\n- Adequate sleep — 7–8 hours of quality sleep nightly.\n- Regular **Panchakarma therapy** — Ayurvedic cleansing therapies like *Virechana, Basti* are useful.\n\n### D. Ayurvedic Insights on Diabetes Management\n- *Ekadasha (eleventh) Vidhi vidhana* — daily routine and lifestyle guidance to control diabetes.\n- *Apan Vayu* control — yoga and pranayama balance the lower abdominal energies.\n- Use **copper-vessel water** — drinking water stored in copper helps to maintain blood-sugar balance.\n- Practise *Abhyanga (oil massage)* — improves circulation, reduces stress, and lowers sugar levels.\n- Track sugar levels at home — using a glucometer ensures consistent monitoring."}
  ]'::jsonb,
  '[
    {"name":"Vrida Vijaysar","price":265,"url":"/shop"},
    {"name":"Vrida Madhunashini","price":225,"url":"/shop"},
    {"name":"Vrida Karela-Jamun Juice","price":189,"url":"/shop"},
    {"name":"Vrida Methi Capsules","price":175,"url":"/shop"}
  ]'::jsonb,
  '[
    {"q":"Can Ayurveda reverse diabetes?","a":"Early-stage Type 2 diabetes can often be reversed with consistent Ayurvedic medicine, strict diet and exercise. Long-standing or Type 1 diabetes can be well-managed but not reversed."},
    {"q":"Can I stop my allopathic diabetes medicine after starting Ayurveda?","a":"Never stop suddenly. Reduce only under joint supervision of your physician and Ayurvedic doctor as sugar levels improve."},
    {"q":"How often should I check my blood sugar?","a":"Fasting and post-meal checks 2–3 times a week initially; HbA1c every 3 months."}
  ]'::jsonb
),
(
  'high-cholesterol', 'High Cholesterol',
  'Lower bad cholesterol and protect your heart, naturally.',
  'High Cholesterol — Causes, Symptoms & Ayurvedic Remedies',
  'Manage LDL, triglycerides and overall heart health with classical herbs and lifestyle correction.',
  true, 31, (SELECT id FROM ncd),
  'Talk to an Ayurveda Doctor',
  '[
    {"key":"overview","title":"Overview","body_markdown":"High cholesterol is a medical condition in which fatty substances (lipids) accumulate in the blood, which can lead to several health complications, including atherosclerosis. Cholesterol is a fatty substance that is necessary for building healthy cells, but too much of it can increase the risk of heart disease.\n\nCholesterol is carried through the bloodstream by lipoproteins, with two main types — **Low-density lipoprotein (LDL)**, often referred to as the ''bad cholesterol'', and **High-density lipoprotein (HDL)**, known as ''good cholesterol''. When LDL levels become too high, it can lead to plaque buildup in the arteries, narrowing them and causing serious cardiovascular issues like heart attack or stroke.\n\nHigh cholesterol often develops silently with no warning signs, making it crucial to have regular blood tests. Ayurveda views this condition as a *Kapha–Medas* imbalance and offers natural ways to manage symptoms and overall heart health and well-being."},
    {"key":"causes","title":"Causes","body_markdown":"### A. Dietary Factors\n- **Excessive consumption of saturated and trans fats** — found in fried foods, red meat and processed foods.\n- **High intake of sugary foods** — excess sugar is converted into fat, leading to fat-imbalance.\n- **Refined carbohydrates** — white rice, white bread and pasta also contribute to cholesterol imbalance.\n- **Alcohol intake** — excessive alcohol consumption raises LDL cholesterol levels in the blood.\n\n### B. Lifestyle Factors\n- **Sedentary lifestyle** — lack of exercise reduces HDL (good) cholesterol and increases LDL.\n- **Smoking** — tobacco lowers HDL and damages blood vessel walls.\n- **Stress** — chronic stress increases cortisol, which negatively affects cholesterol levels.\n- **Obesity** — being overweight contributes to higher cholesterol levels.\n\n### C. Underlying Health Conditions\n- **Diabetes** — high blood-sugar levels can also affect cholesterol.\n- **Hypothyroidism** — slow metabolism leads to poor breakdown of cholesterol.\n- **Liver disease** — the liver plays a key role in producing and regulating cholesterol.\n- **Kidney issues** — chronic kidney disease can lead to imbalanced lipid profiles.\n- **Genetic factors** — familial hypercholesterolaemia is an inherited condition affecting cholesterol metabolism.\n\n### D. Ayurvedic Causes of High Cholesterol\n- **Kapha–Medas dushti** — overconsumption of heavy, oily and rich foods.\n- **Low Agni (weak digestion)** — poor digestive fire creates *ama*, leading to fat blockages.\n- **Avara Vyayama** — lack of physical activity worsens Kapha and Medas.\n- **Manas Stress** — emotional stress increases sympathetic activity and affects metabolism."},
    {"key":"symptoms","title":"Symptoms","body_markdown":"High cholesterol often shows no symptoms in its early stages. It is often called a ''silent disease''. Some signs of complications include:\n\n### A. Cardiovascular Symptoms\n- **Chest pain (angina)** — caused by reduced blood flow due to clogged arteries.\n- **High blood pressure** — often a result of cholesterol-related blockages.\n- **Shortness of breath** — when the heart cannot get enough oxygen.\n- **Heart attack** — chest pain or discomfort that may radiate to the arm or jaw.\n- **Stroke** — sudden numbness, weakness or trouble speaking.\n\n### B. Neurological Symptoms\n- **Memory issues** — high cholesterol affects brain function.\n- **Numbness or tingling** in extremities — caused by poor blood flow.\n\n### C. Physical Symptoms\n- **Xanthomas** — yellow fatty deposits on the skin, especially around the eyes.\n- **Fatigue** — when the heart and circulatory system are under strain.\n- **Atherosclerosis** — when fatty deposits accumulate in arteries."},
    {"key":"remedies","title":"Ayurvedic Remedies","body_markdown":"### A. Herbal Remedies\n- **Triphala** — detoxifies the digestive system and assists in fat metabolism.\n- **Guggul** *(Commiphora mukul)* — well-known to reduce LDL and total cholesterol.\n- **Arjuna** *(Terminalia arjuna)* — strengthens the heart muscle and regulates the rhythm.\n- **Ashwagandha** — reduces stress, indirectly preventing cholesterol-rise.\n- **Punarnava** — diuretic, supports liver and reduces fat retention.\n- **Garlic + Onion** — natural blood thinners; reduce LDL.\n- **Cinnamon** *(Dalchini)* — improves lipid profile; lowers blood-sugar.\n\n### B. Ayurvedic Diet for Cholesterol Management\n- Daily **Triphala kashaya** — detoxifies, helps cholesterol regulation.\n- Eat warm, light, freshly cooked food — easy to digest, reduces *ama*.\n- Increase dietary fibre — oats, barley, beans, fruits and vegetables.\n- Use **healthy fats** — cold-pressed sesame, olive or mustard oil; avoid trans fats.\n- Drink warm water through the day, especially with lemon.\n- Avoid heavy, deep-fried, sweet and processed foods; they aggravate Kapha-Medas.\n\n### C. Lifestyle Modifications\n- **Daily Vyayama (exercise)** — at least 45 minutes of brisk walk, jog or yoga.\n- Yoga: *Sarvangasana, Halasana, Ardha Matsyendrasana, Pranayama (Bhastrika, Kapalabhati)*.\n- **Pranayama** — *Anuloma-Viloma, Bhastrika* clear *srotas* and calm stress.\n- Maintain healthy weight — even 5–10% loss improves lipid profile.\n- Sleep before 10:30 PM — disturbed sleep increases cholesterol.\n- **Abhyanga** *(daily oil massage)* — improves circulation, reduces stress."}
  ]'::jsonb,
  '[
    {"name":"Vrida Arjuna","price":225,"url":"/shop"},
    {"name":"Vrida Guggul Tablet","price":189,"url":"/shop"},
    {"name":"Vrida Triphala","price":159,"url":"/shop"},
    {"name":"Vrida Heart Care Kit","price":499,"url":"/shop"}
  ]'::jsonb,
  '[
    {"q":"How long does it take to lower cholesterol with Ayurveda?","a":"With consistent herbal treatment, diet correction and exercise, most people see improvement in 8–12 weeks."},
    {"q":"Can I stop statins after starting Ayurveda?","a":"Only under joint supervision of your cardiologist and Ayurvedic doctor. Never stop statins abruptly."},
    {"q":"Is ghee bad for cholesterol?","a":"Pure cow ghee in small quantities (1–2 tsp/day) actually supports lipid metabolism. Avoid hydrogenated/vanaspati ghee."}
  ]'::jsonb
),
(
  'thyroid', 'Thyroid (Hypo & Hyperthyroidism)',
  'Restore thyroid balance and energy naturally.',
  'Thyroid Disorders — Causes, Symptoms & Ayurvedic Remedies',
  'Manage hypothyroidism, hyperthyroidism and Hashimoto with classical Ayurveda + lifestyle care.',
  true, 32, (SELECT id FROM ncd),
  'Talk to an Ayurveda Doctor',
  '[
    {"key":"overview","title":"Overview","body_markdown":"Thyroid disease is a common condition that affects the thyroid gland — a butterfly-shaped organ located at the base of the neck. The thyroid produces hormones that regulate metabolism, energy levels, body temperature and growth. When the thyroid produces too much or too little hormone, it leads to **hypothyroidism** (underactive) or **hyperthyroidism** (overactive), affecting overall health and well-being.\n\nThe most common conditions are **hypothyroidism**, where the thyroid produces too little hormone, and **hyperthyroidism**, where it produces too much. Other thyroid issues include thyroid nodules, goitre and thyroid cancer. Ayurveda associates thyroid imbalance with vitiation of ***Kapha–Vata doshas*** and weak ***Agni*** in the *galaganda* (neck) region, leading to either an overactive or underactive thyroid gland.\n\nManaging thyroid disorders involves a combination of medical treatment, dietary changes, and lifestyle modifications. With timely intervention and proper care, many people lead a healthy and balanced life despite having a thyroid disorder. Ayurvedic medicine can offer natural treatments to support thyroid health and overall well-being."},
    {"key":"causes","title":"Causes","body_markdown":"### A. Genetic & Autoimmune Causes\n- **Hashimoto thyroiditis** — autoimmune attack causing hypothyroidism.\n- **Graves disease** — autoimmune cause of hyperthyroidism.\n- **Family history** — thyroid disorders run in families.\n\n### B. Iodine Imbalance\n- **Iodine deficiency** — leading global cause of goitre and hypothyroidism.\n- **Excess iodine** — can also trigger thyroid dysfunction.\n\n### C. Lifestyle & Environmental\n- **Chronic stress** — disturbs the HPA axis and thyroid output.\n- **Selenium / zinc deficiency** — impacts thyroid hormone conversion.\n- **Pregnancy and postpartum** — common trigger for thyroid changes.\n- **Radiation exposure / certain medications** — affect thyroid function.\n- **Smoking and alcohol** — disturb thyroid metabolism.\n\n### D. Ayurvedic Causes\n- *Kapha–Medas* obstruction in the neck region (***Galaganda***).\n- Weak *Agni* (digestion) leading to *ama* accumulation.\n- *Vata aggravation* causing dryness, weight loss and palpitations (hyperthyroid).\n- *Kapha aggravation* causing weight gain, lethargy, cold intolerance (hypothyroid)."},
    {"key":"symptoms","title":"Symptoms","body_markdown":"### A. Hypothyroidism (Underactive)\n- Fatigue, low energy\n- Weight gain despite reduced appetite\n- Cold intolerance, dry skin and hair\n- Constipation\n- Depression, brain fog, memory issues\n- Hair fall, brittle nails\n- Heavy or irregular periods\n- Puffiness around eyes, swollen face\n- Slow heart rate\n\n### B. Hyperthyroidism (Overactive)\n- Unexplained weight loss\n- Anxiety, irritability, restlessness\n- Rapid or irregular heartbeat (palpitations)\n- Heat intolerance, excessive sweating\n- Tremors in hands\n- Insomnia, difficulty sleeping\n- Frequent bowel movements / diarrhoea\n- Bulging eyes (in Graves disease)\n- Light or absent periods\n\n### C. Goitre / Nodules\n- Visible swelling at base of the neck\n- Difficulty swallowing or breathing in large goitre\n- Hoarseness of voice"},
    {"key":"remedies","title":"Ayurvedic Remedies","body_markdown":"### A. Classical Herbs\n- **Kanchanara Guggulu** — gold-standard for *galaganda*; reduces goitre and nodules.\n- **Ashwagandha** — adaptogen; supports both hypo- and hyperthyroidism by balancing stress.\n- **Brahmi + Shankhpushpi** — calm the nervous system in hyperthyroid.\n- **Guggul + Triphala** — clear *srotas* and Kapha–Medas obstruction.\n- **Varun, Punarnava** — reduce neck swelling and water retention.\n- **Shilajit** — supports endocrine function and energy.\n\n### B. Diet for Hypothyroidism\n- Include **iodine-rich foods** — rock salt, sea vegetables (in moderation), curd.\n- Selenium-rich foods — Brazil nuts, sunflower seeds, mushrooms.\n- Warm, light, freshly cooked meals; avoid cold drinks.\n- Avoid raw cruciferous vegetables in excess (broccoli, cabbage) — they affect thyroid.\n- Reduce gluten, sugar, processed foods.\n\n### C. Diet for Hyperthyroidism\n- Cooling foods — coconut water, cucumber, melons.\n- Limit caffeine, spicy, sour, fermented foods (Pitta-aggravating).\n- Adequate protein and complex carbs.\n- Avoid iodised salt in excess.\n\n### D. Lifestyle\n- Yoga: *Sarvangasana, Halasana, Matsyasana, Ujjayi pranayama* — direct thyroid stimulation.\n- For hyperthyroid — *Shitali pranayama, Yoga Nidra* to calm.\n- Sleep 7–8 hours; reduce screen time before bed.\n- Daily *Abhyanga* with sesame oil; warm in winter.\n- Stress management — meditation, journaling.\n\n### E. When to Take Allopathic Medicine\nThyroxine (Eltroxin) and antithyroid drugs save lives in moderate-to-severe cases. Ayurveda works best as **integrative care** — never replace prescribed thyroid medicine without your endocrinologist''s guidance. With Ayurvedic support, doses of allopathic medicine often reduce over time."}
  ]'::jsonb,
  '[
    {"name":"Kanchanara Guggulu","price":265,"url":"/shop"},
    {"name":"Vrida Ashwagandha","price":225,"url":"/shop"},
    {"name":"Vrida Thyroid Support Kit","price":549,"url":"/shop"},
    {"name":"Vrida Brahmi","price":189,"url":"/shop"}
  ]'::jsonb,
  '[
    {"q":"Can Ayurveda cure thyroid disease?","a":"Early-stage and mild thyroid imbalance can be reversed. Autoimmune cases (Hashimoto, Graves) are managed long-term with reduced medicine dosage."},
    {"q":"Can I stop thyroxine after starting Ayurveda?","a":"Never stop suddenly. Reduce only under joint supervision of your endocrinologist and Ayurvedic doctor as TSH normalises."},
    {"q":"How often to check thyroid levels?","a":"TSH every 6–8 weeks initially, then every 3–6 months once stable."}
  ]'::jsonb
)
ON CONFLICT (slug) DO UPDATE SET
  content_sections = EXCLUDED.content_sections,
  related_medicines = EXCLUDED.related_medicines,
  faqs = EXCLUDED.faqs,
  tagline = EXCLUDED.tagline,
  hero_title = EXCLUDED.hero_title,
  hero_subtitle = EXCLUDED.hero_subtitle,
  system_id = EXCLUDED.system_id,
  consult_banner_text = EXCLUDED.consult_banner_text,
  is_published = true,
  updated_at = now();