import { useEffect, useMemo, useState } from "react";
import { Loader2, MapPin } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";

type Session = { id:string; patient_name:string; therapy_name:string; therapy_code:string; scheduled_date:string; scheduled_start:string; scheduled_duration_minutes:number; actual_duration_minutes:number|null; status:string|null; payment_status:string|null; total_amount:number; patient_user_id:string|null; razorpay_payment_id:string|null; therapists:{id:string;full_name:string}|null; therapy_venues:{id:string;name:string}|null; };
type Therapist = { id:string; full_name:string; allowed_therapies:string[] | null };
type Venue = { id:string; name:string };
type Ping = { id:string; pinged_at:string; lat:number; lng:number };
const money = (n:number) => new Intl.NumberFormat("en-IN", { style:"currency", currency:"INR", maximumFractionDigits:0 }).format(n||0);

const AdminSessions = () => {
  const [rows,setRows]=useState<Session[]>([]); const [therapists,setTherapists]=useState<Therapist[]>([]); const [venues,setVenues]=useState<Venue[]>([]); const [loading,setLoading]=useState(true);
  const [status,setStatus]=useState("all"); const [therapist,setTherapist]=useState("all"); const [venue,setVenue]=useState("all"); const [therapy,setTherapy]=useState("all"); const [from,setFrom]=useState(""); const [to,setTo]=useState("");
  const [cancelFor,setCancelFor]=useState<Session|null>(null); const [reason,setReason]=useState(""); const [reassignFor,setReassignFor]=useState<Session|null>(null); const [newTherapist,setNewTherapist]=useState(""); const [pingFor,setPingFor]=useState<Session|null>(null); const [pings,setPings]=useState<Ping[]>([]);
  const load=async()=>{setLoading(true); const [{data,error},{data:ts},{data:vs}]=await Promise.all([(supabase as any).from("therapy_sessions").select("id,patient_name,therapy_name,therapy_code,scheduled_date,scheduled_start,scheduled_duration_minutes,actual_duration_minutes,status,payment_status,total_amount,patient_user_id,razorpay_payment_id,therapists(id,full_name),therapy_venues(id,name)").order("scheduled_date",{ascending:false}).limit(300), supabase.from("therapists").select("id,full_name,allowed_therapies").eq("is_verified",true), supabase.from("therapy_venues").select("id,name").eq("is_verified",true)]); if(error) toast.error(error.message); setRows((data??[]) as Session[]); setTherapists((ts??[]) as Therapist[]); setVenues((vs??[]) as Venue[]); setLoading(false);};
  useEffect(()=>{document.title="Therapy Sessions — Admin"; load();},[]);
  const therapies=[...new Set(rows.map(r=>r.therapy_name).filter(Boolean))];
  const filtered=useMemo(()=>rows.filter(s=>{ if(status!=="all"&&s.status!==status)return false; if(therapist!=="all"&&s.therapists?.id!==therapist)return false; if(venue!=="all"&&s.therapy_venues?.id!==venue)return false; if(therapy!=="all"&&s.therapy_name!==therapy)return false; if(from&&s.scheduled_date<from)return false; if(to&&s.scheduled_date>to)return false; return true;}),[rows,status,therapist,venue,therapy,from,to]);
  const update=async(id:string,patch:Record<string,unknown>)=>{const {error}=await (supabase as any).from("therapy_sessions").update(patch).eq("id",id); if(error)return toast.error(error.message); toast.success("Session updated"); load();};
  const openPings=async(s:Session)=>{setPingFor(s); const {data,error}=await supabase.from("therapist_location_pings").select("id,pinged_at,lat,lng").eq("session_id",s.id).order("pinged_at",{ascending:false}); if(error)toast.error(error.message); setPings((data??[]) as Ping[]);};
  return <div className="space-y-6"><div><h1 className="font-display text-3xl">Therapy Sessions</h1><p className="text-sm text-muted-foreground">Manage session delivery, reassignment, location pings, and refunds.</p></div>
  <Card><CardContent className="flex flex-wrap gap-3 p-4"><Select value={status} onValueChange={setStatus}><SelectTrigger className="w-44"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All statuses</SelectItem>{["scheduled","therapist_assigned","in_progress","completed","cancelled"].map(s=><SelectItem key={s} value={s}>{s.replace(/_/g," ")}</SelectItem>)}</SelectContent></Select><Select value={therapist} onValueChange={setTherapist}><SelectTrigger className="w-52"><SelectValue placeholder="Therapist" /></SelectTrigger><SelectContent><SelectItem value="all">All therapists</SelectItem>{therapists.map(t=><SelectItem key={t.id} value={t.id}>{t.full_name}</SelectItem>)}</SelectContent></Select><Select value={venue} onValueChange={setVenue}><SelectTrigger className="w-52"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All venues</SelectItem>{venues.map(v=><SelectItem key={v.id} value={v.id}>{v.name}</SelectItem>)}</SelectContent></Select><Select value={therapy} onValueChange={setTherapy}><SelectTrigger className="w-52"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All therapies</SelectItem>{therapies.map(t=><SelectItem key={t} value={t}>{t}</SelectItem>)}</SelectContent></Select><Input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="w-40"/><Input type="date" value={to} onChange={e=>setTo(e.target.value)} className="w-40"/></CardContent></Card>
  <Card><CardContent className="p-0">{loading?<div className="grid place-items-center py-12"><Loader2 className="h-6 w-6 animate-spin"/></div>:<Table><TableHeader><TableRow><TableHead>Patient</TableHead><TableHead>Therapy</TableHead><TableHead>Therapist</TableHead><TableHead>Venue</TableHead><TableHead>Schedule</TableHead><TableHead>Duration</TableHead><TableHead>Status</TableHead><TableHead>Payment</TableHead><TableHead className="text-right">Amount</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{filtered.map(s=>{const short=!!s.actual_duration_minutes&&s.actual_duration_minutes<s.scheduled_duration_minutes*0.7;return <TableRow key={s.id}><TableCell>{s.patient_name}</TableCell><TableCell>{s.therapy_name}<div className="text-xs text-muted-foreground">{s.therapy_code}</div></TableCell><TableCell>{s.therapists?.full_name??"—"}</TableCell><TableCell>{s.therapy_venues?.name??"—"}</TableCell><TableCell>{s.scheduled_date}<div className="text-xs text-muted-foreground">{s.scheduled_start?.slice(0,5)}</div></TableCell><TableCell>{s.actual_duration_minutes??"—"}/{s.scheduled_duration_minutes} min {short&&<Badge variant="destructive" className="ml-1">⚠ Short session</Badge>}</TableCell><TableCell><Badge variant="outline">{s.status?.replace(/_/g," ")}</Badge></TableCell><TableCell><Badge variant={s.payment_status==="paid"?"default":"outline"}>{s.payment_status}</Badge></TableCell><TableCell className="text-right font-semibold">{money(s.total_amount)}</TableCell><TableCell className="text-right whitespace-nowrap space-x-1"><Button size="sm" variant="ghost" onClick={()=>openPings(s)}><MapPin /></Button>{s.status!=="completed"&&s.status!=="cancelled"&&<><Button size="sm" variant="outline" onClick={()=>{setReassignFor(s);setNewTherapist("");}}>Reassign</Button><Button size="sm" variant="destructive" onClick={()=>setCancelFor(s)}>Cancel</Button></>}</TableCell></TableRow>})}{filtered.length===0&&<TableRow><TableCell colSpan={10} className="py-8 text-center text-muted-foreground">No sessions found.</TableCell></TableRow>}</TableBody></Table>}</CardContent></Card>
  <Dialog open={!!cancelFor} onOpenChange={o=>!o&&setCancelFor(null)}><DialogContent><DialogHeader><DialogTitle>Cancel session</DialogTitle></DialogHeader><p className="text-sm text-muted-foreground">Paid sessions will be marked refund_pending for Razorpay review.</p><Textarea placeholder="Refund / cancellation reason" value={reason} onChange={e=>setReason(e.target.value)}/><DialogFooter><Button variant="outline" onClick={()=>setCancelFor(null)}>Back</Button><Button variant="destructive" onClick={()=>{if(cancelFor)update(cancelFor.id,{status:"cancelled",payment_status:cancelFor.payment_status==="paid"?"refund_pending":cancelFor.payment_status,therapist_notes:reason});setCancelFor(null);setReason("");}}>Cancel session</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={!!reassignFor} onOpenChange={o=>!o&&setReassignFor(null)}><DialogContent><DialogHeader><DialogTitle>Reassign therapist</DialogTitle></DialogHeader><Select value={newTherapist} onValueChange={setNewTherapist}><SelectTrigger><SelectValue placeholder="Choose certified therapist"/></SelectTrigger><SelectContent>{therapists.filter(t=>!reassignFor||(t.allowed_therapies??[]).includes(reassignFor.therapy_code)).map(t=><SelectItem key={t.id} value={t.id}>{t.full_name}</SelectItem>)}</SelectContent></Select><DialogFooter><Button variant="outline" onClick={()=>setReassignFor(null)}>Back</Button><Button disabled={!newTherapist} onClick={()=>{if(reassignFor)update(reassignFor.id,{therapist_id:newTherapist,status:"therapist_assigned"});setReassignFor(null);}}>Reassign</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={!!pingFor} onOpenChange={o=>!o&&setPingFor(null)}><DialogContent><DialogHeader><DialogTitle>Location pings</DialogTitle></DialogHeader><div className="max-h-80 space-y-2 overflow-auto">{pings.map(p=><div key={p.id} className="rounded-md border border-border p-3 text-sm"><p>{new Date(p.pinged_at).toLocaleString("en-IN")}</p><p className="text-muted-foreground">{p.lat}, {p.lng}</p></div>)}{pings.length===0&&<p className="text-sm text-muted-foreground">No pings recorded.</p>}</div></DialogContent></Dialog>
  </div>;
};
export default AdminSessions;
