import { useEffect, useMemo, useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

type Order = { total: number; created_at: string; appointment_id?: string | null };
type Appt = { appointment_date: string; status: string; fee: number; doctor_id: string; doctors?: { full_name: string } | null };
type Role = { created_at: string; role: string };
const money = (n: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(n || 0);
const keyWeek = (d: Date) => `${d.getFullYear()}-W${Math.ceil((((d.getTime() - new Date(d.getFullYear(),0,1).getTime()) / 86400000) + new Date(d.getFullYear(),0,1).getDay() + 1) / 7)}`;

const AdminReports = () => {
  const [orders, setOrders] = useState<Order[]>([]); const [appointments, setAppointments] = useState<Appt[]>([]); const [roles, setRoles] = useState<Role[]>([]);
  useEffect(() => { document.title = "Reports — Admin"; (async () => { const sinceYear = new Date(); sinceYear.setMonth(sinceYear.getMonth() - 12); const sinceWeek = new Date(); sinceWeek.setDate(sinceWeek.getDate() - 84); const [o, a, r] = await Promise.all([supabase.from("orders").select("total,created_at,appointment_id").eq("payment_status", "paid").gte("created_at", sinceYear.toISOString()), supabase.from("appointments").select("appointment_date,status,fee,doctor_id,doctors(full_name)").gte("appointment_date", sinceWeek.toISOString().slice(0, 10)), supabase.from("user_roles").select("created_at,role").gte("created_at", sinceWeek.toISOString())]); setOrders((o.data ?? []) as Order[]); setAppointments((a.data ?? []) as Appt[]); setRoles((r.data ?? []) as Role[]); })(); }, []);
  const growth = useMemo(() => { const out: Record<string, any> = {}; for (let i = 11; i >= 0; i--) { const d = new Date(); d.setDate(d.getDate() - i * 7); out[keyWeek(d)] = { week: keyWeek(d), patient: 0, doctor: 0, therapist: 0, student: 0 }; } roles.forEach(r => { const k = keyWeek(new Date(r.created_at)); if (out[k]) out[k][r.role] = (out[k][r.role] || 0) + 1; }); return Object.values(out); }, [roles]);
  const monthly = useMemo(() => { const out: Record<string, number> = {}; for (let i = 11; i >= 0; i--) { const d = new Date(); d.setMonth(d.getMonth() - i); out[d.toISOString().slice(0,7)] = 0; } orders.forEach(o => { const k = o.created_at.slice(0,7); if (k in out) out[k] += o.total; }); return Object.entries(out).map(([month, revenue]) => ({ month, revenue })); }, [orders]);
  const apptWeekly = useMemo(() => { const out: Record<string, number> = {}; appointments.forEach(a => { const k = keyWeek(new Date(a.appointment_date)); out[k] = (out[k] || 0) + 1; }); return Object.entries(out).map(([week, count]) => ({ week, count })).slice(-12); }, [appointments]);
  const topDoctors = useMemo(() => Object.values(appointments.reduce((acc: Record<string, any>, a) => { const k = a.doctor_id || "unknown"; acc[k] ||= { name: a.doctors?.full_name || "Doctor", appointments: 0, revenue: 0 }; acc[k].appointments += 1; acc[k].revenue += a.fee || 0; return acc; }, {})).sort((a:any,b:any) => b.appointments - a.appointments).slice(0,10), [appointments]);
  const totalAppts = appointments.length || 1; const completed = appointments.filter(a => a.status === "completed").length; const cancelled = appointments.filter(a => a.status === "cancelled").length;
  return <div className="space-y-6"><div><h1 className="font-display text-3xl">Reports & Analytics</h1><p className="text-sm text-muted-foreground">Printable growth, revenue, appointment, and doctor performance reports.</p></div><Tabs defaultValue="growth"><TabsList className="flex h-auto flex-wrap justify-start"><TabsTrigger value="growth">User Growth</TabsTrigger><TabsTrigger value="revenue">Revenue</TabsTrigger><TabsTrigger value="appointments">Appointments</TabsTrigger><TabsTrigger value="doctors">Top Doctors</TabsTrigger></TabsList>
  <TabsContent value="growth"><ReportCard title="User Growth" onPrint={() => window.print()}><ResponsiveContainer width="100%" height={340}><LineChart data={growth}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="week" /><YAxis /><Tooltip /><Legend /><Line dataKey="patient" stroke="hsl(var(--primary))" /><Line dataKey="doctor" stroke="hsl(var(--admin-success))" /><Line dataKey="therapist" stroke="hsl(var(--admin-warning))" /><Line dataKey="student" stroke="hsl(var(--admin-danger))" /></LineChart></ResponsiveContainer></ReportCard></TabsContent>
  <TabsContent value="revenue"><div className="grid gap-6 lg:grid-cols-[1.4fr_0.6fr]"><ReportCard title="Monthly Revenue" onPrint={() => window.print()}><ResponsiveContainer width="100%" height={340}><AreaChart data={monthly}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="month" /><YAxis /><Tooltip /><Area dataKey="revenue" fill="hsl(var(--primary) / 0.2)" stroke="hsl(var(--primary))" /></AreaChart></ResponsiveContainer></ReportCard><ReportCard title="Breakdown" onPrint={() => window.print()}><ResponsiveContainer width="100%" height={300}><PieChart><Pie data={[{name:"Consultation",value:appointments.reduce((s,a)=>s+(a.fee||0),0)},{name:"Medicine",value:orders.reduce((s,o)=>s+(o.appointment_id?0:o.total),0)},{name:"Therapy",value:orders.reduce((s,o)=>s+(o.appointment_id?o.total:0),0)}]} dataKey="value" nameKey="name"><Cell fill="hsl(var(--primary))"/><Cell fill="hsl(var(--admin-success))"/><Cell fill="hsl(var(--admin-warning))"/></Pie><Tooltip formatter={(v)=>money(Number(v))}/></PieChart></ResponsiveContainer></ReportCard></div></TabsContent>
  <TabsContent value="appointments"><ReportCard title={`Appointments · Completion ${Math.round(completed/totalAppts*100)}% · Cancellation ${Math.round(cancelled/totalAppts*100)}%`} onPrint={() => window.print()}><ResponsiveContainer width="100%" height={340}><BarChart data={apptWeekly}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="week" /><YAxis /><Tooltip /><Bar dataKey="count" fill="hsl(var(--primary))" /></BarChart></ResponsiveContainer></ReportCard></TabsContent>
  <TabsContent value="doctors"><ReportCard title="Top Doctors" onPrint={() => window.print()}><Table><TableHeader><TableRow><TableHead>Doctor</TableHead><TableHead className="text-right">Appointments</TableHead><TableHead className="text-right">Revenue</TableHead></TableRow></TableHeader><TableBody>{topDoctors.map((d:any)=><TableRow key={d.name}><TableCell>{d.name}</TableCell><TableCell className="text-right">{d.appointments}</TableCell><TableCell className="text-right">{money(d.revenue)}</TableCell></TableRow>)}</TableBody></Table></ReportCard></TabsContent>
  </Tabs></div>;
};
const ReportCard = ({ title, children, onPrint }: { title: string; children: React.ReactNode; onPrint: () => void }) => <Card><CardHeader><CardTitle className="flex items-center justify-between gap-3"><span>{title}</span><Button size="sm" variant="outline" onClick={onPrint}>Download Report</Button></CardTitle></CardHeader><CardContent>{children}</CardContent></Card>;
export default AdminReports;
