import {  useEffect, useState  } from "react";
import { usePageSEO } from "@/hooks/usePageSEO";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";

type Log = { id:string; recipient_phone:string|null; recipient_name:string|null; template_name:string|null; message_preview:string|null; status:string; sent_at:string };
type Recipient = { phone:string|null; full_name?:string|null };
const AdminNotifications=()=>{
  usePageSEO({ title: "Notifications — Admin", noIndex: true });const [target,setTarget]=useState("all");const [phone,setPhone]=useState("");const [message,setMessage]=useState("");const [logs,setLogs]=useState<Log[]>([]);const [sending,setSending]=useState(false);
 const load=async()=>{const {data}=await (supabase as any).from("notification_logs").select("*").order("sent_at",{ascending:false}).limit(50);setLogs(data??[])}; useEffect(() => { load()},[]);
 const recipients=async():Promise<Recipient[]>=>{ if(target==="specific") return [{phone,full_name:"Specific user"}]; if(target==="doctors"){const {data}=await supabase.from("doctors").select("phone,full_name");return data??[]} if(target==="therapists"){const {data}=await supabase.from("therapists").select("phone,full_name");return data??[]} const {data}=await supabase.from("profiles").select("phone,full_name"); return (data??[]).filter((r:any)=>r.phone); };
 const send=async()=>{if(!message.trim())return toast.error("Enter a message");setSending(true);const list=(await recipients()).filter(r=>r.phone).slice(0,50);for(const r of list){await supabase.functions.invoke("send-whatsapp",{body:{to:r.phone,message}});await (supabase as any).from("notification_logs").insert({recipient_phone:r.phone,recipient_name:r.full_name,template_name:"admin_broadcast",message_preview:message.slice(0,120),status:"sent"});}toast.success(`Sent ${list.length} WhatsApp notifications`);setSending(false);load()};
 return <div className="space-y-6"><div><h1 className="font-display text-3xl">Notifications</h1><p className="text-sm text-muted-foreground">Send WhatsApp broadcasts and review recent notification logs.</p></div><Card><CardHeader><CardTitle>Send Custom Broadcast</CardTitle></CardHeader><CardContent className="grid gap-4"><div className="grid gap-4 md:grid-cols-2"><div><Label>Target audience</Label><Select value={target} onValueChange={setTarget}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{[["all","All Users"],["doctors","All Doctors"],["therapists","All Therapists"],["patients","All Patients"],["students","All Students"],["specific","Specific user"]].map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></div>{target==="specific"&&<div><Label>Phone</Label><Input value={phone} onChange={e=>setPhone(e.target.value)} /></div>}</div><Textarea rows={5} value={message} onChange={e=>setMessage(e.target.value)} placeholder="WhatsApp template or message"/><Button onClick={send} disabled={sending}>{sending?"Sending…":"Send broadcast"}</Button></CardContent></Card><Card><CardHeader><CardTitle>Notification Log</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Recipient</TableHead><TableHead>Phone</TableHead><TableHead>Message</TableHead><TableHead>Status</TableHead><TableHead>Sent</TableHead></TableRow></TableHeader><TableBody>{logs.map(l=><TableRow key={l.id}><TableCell>{l.recipient_name??"—"}</TableCell><TableCell>{l.recipient_phone}</TableCell><TableCell className="max-w-md truncate">{l.message_preview}</TableCell><TableCell>{l.status}</TableCell><TableCell>{new Date(l.sent_at).toLocaleString("en-IN")}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card></div>};
export default AdminNotifications;
