import { useEffect, useMemo, useState } from "react";
import { ChevronDown, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";

type Item = { id:string; product_name:string; quantity:number; unit_price:number };
type Order = { id:string; user_id:string; full_name:string; phone:string; subtotal:number; total:number; payment_status:string; order_status:string; delhivery_waybill:string|null; created_at:string; order_items?:Item[]; patient?:{full_name?:string|null;phone?:string|null}|null; razorpay_payment_id?:string|null };
const statuses=["placed","confirmed","packed","shipped","out_for_delivery","delivered"];
const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n||0);
const today=()=>new Date().toISOString().slice(0,10);

const AdminOrders=()=>{
 const [rows,setRows]=useState<Order[]>([]); const [loading,setLoading]=useState(true); const [expanded,setExpanded]=useState<string|null>(null);
 const [status,setStatus]=useState("all"); const [payment,setPayment]=useState("all"); const [from,setFrom]=useState(""); const [to,setTo]=useState(""); const [search,setSearch]=useState(""); const [cancelFor,setCancelFor]=useState<Order|null>(null); const [reason,setReason]=useState("");
 const load=async()=>{setLoading(true); const {data,error}=await (supabase as any).from("orders").select("id,user_id,full_name,phone,subtotal,total,payment_status,order_status,delhivery_waybill,created_at,razorpay_payment_id,order_items(id,product_name,quantity,unit_price)").order("created_at",{ascending:false}).limit(300); if(error)toast.error(error.message); const orders=(data??[]) as Order[]; const ids=[...new Set(orders.map(o=>o.user_id).filter(Boolean))]; const {data:profiles}=ids.length?await supabase.from("profiles").select("user_id,full_name,phone").in("user_id",ids):{data:[]} as any; const map=new Map((profiles??[]).map((p:any)=>[p.user_id,p])); setRows(orders.map(o=>({...o,patient:map.get(o.user_id)??null}))); setLoading(false);};
 useEffect(()=>{document.title="Orders — Admin";load();},[]);
 const filtered=useMemo(()=>rows.filter(o=>{if(status!=="all"&&o.order_status!==status)return false; if(payment!=="all"&&o.payment_status!==payment)return false; const day=o.created_at.slice(0,10); if(from&&day<from)return false; if(to&&day>to)return false; if(search&&!`${o.id} ${o.full_name} ${o.patient?.full_name??""}`.toLowerCase().includes(search.toLowerCase()))return false; return true;}),[rows,status,payment,from,to,search]);
 const updateStatus=async(o:Order,next:string)=>{let patch:Record<string,unknown>={order_status:next}; if(next==="shipped"&&!o.delhivery_waybill){const {data}=await supabase.functions.invoke("create-delhivery-shipment",{body:{order_id:o.id}}); if((data as any)?.waybill) patch.delhivery_waybill=(data as any).waybill; else toast.info("Shipment requested; waybill not returned yet");} const {error}=await (supabase as any).from("orders").update(patch).eq("id",o.id); if(error)return toast.error(error.message); toast.success("Order updated"); load();};
 const cancel=async()=>{if(!cancelFor)return; const {error}=await (supabase as any).from("orders").update({order_status:"cancelled",payment_status:cancelFor.payment_status==="paid"?"refund_pending":cancelFor.payment_status}).eq("id",cancelFor.id); if(error)return toast.error(error.message); toast.success("Order cancelled; refund queued if applicable"); setCancelFor(null); setReason(""); load();};
 return <div className="space-y-6"><div><h1 className="font-display text-3xl">Orders</h1><p className="text-sm text-muted-foreground">Manage medicine orders, dispatches, items, and refunds.</p></div>
 <div className="grid gap-4 md:grid-cols-3"><Stat label="Orders today" value={rows.filter(o=>o.created_at.slice(0,10)===today()).length}/><Stat label="Pending dispatch" value={rows.filter(o=>["placed","confirmed","packed"].includes(o.order_status)).length}/><Card><CardContent className="p-5"><p className="text-sm text-muted-foreground">Revenue today</p><p className="mt-2 font-display text-3xl">{money(rows.filter(o=>o.created_at.slice(0,10)===today()&&o.payment_status==="paid").reduce((a,o)=>a+Number(o.total||0),0))}</p></CardContent></Card></div>
 <Card><CardContent className="flex flex-wrap gap-3 p-4"><Select value={status} onValueChange={setStatus}><SelectTrigger className="w-48"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All order statuses</SelectItem>{statuses.map(s=><SelectItem key={s} value={s}>{s.replace(/_/g," ")}</SelectItem>)}<SelectItem value="cancelled">cancelled</SelectItem></SelectContent></Select><Select value={payment} onValueChange={setPayment}><SelectTrigger className="w-44"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All payments</SelectItem>{["paid","pending","failed","refund_pending"].map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select><Input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="w-40"/><Input type="date" value={to} onChange={e=>setTo(e.target.value)} className="w-40"/><Input placeholder="Search name or order ID" value={search} onChange={e=>setSearch(e.target.value)} className="max-w-xs"/></CardContent></Card>
 <Card><CardContent className="p-0">{loading?<div className="grid place-items-center py-12"><Loader2 className="h-6 w-6 animate-spin"/></div>:<Table><TableHeader><TableRow><TableHead>Order</TableHead><TableHead>Patient</TableHead><TableHead>Phone</TableHead><TableHead>Items</TableHead><TableHead className="text-right">Subtotal</TableHead><TableHead className="text-right">Total</TableHead><TableHead>Payment</TableHead><TableHead>Status</TableHead><TableHead>Waybill</TableHead><TableHead>Created</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{filtered.map(o=><><TableRow key={o.id}><TableCell className="font-mono">AYZ-{o.id.slice(0,8).toUpperCase()}</TableCell><TableCell>{o.patient?.full_name||o.full_name}</TableCell><TableCell>{o.patient?.phone||o.phone}</TableCell><TableCell><Button variant="ghost" size="sm" onClick={()=>setExpanded(expanded===o.id?null:o.id)}>{o.order_items?.length??0}<ChevronDown className="ml-1 h-3 w-3"/></Button></TableCell><TableCell className="text-right">{money(o.subtotal)}</TableCell><TableCell className="text-right font-semibold">{money(o.total)}</TableCell><TableCell><Badge variant={o.payment_status==="paid"?"default":"outline"}>{o.payment_status}</Badge></TableCell><TableCell><Select value={o.order_status} onValueChange={v=>updateStatus(o,v)}><SelectTrigger className="h-8 w-40"><SelectValue/></SelectTrigger><SelectContent>{statuses.map(s=><SelectItem key={s} value={s}>{s.replace(/_/g," ")}</SelectItem>)}</SelectContent></Select></TableCell><TableCell>{o.delhivery_waybill??"—"}</TableCell><TableCell>{new Date(o.created_at).toLocaleDateString("en-IN")}</TableCell><TableCell className="text-right"><Button size="sm" variant="destructive" onClick={()=>setCancelFor(o)}>Cancel & Refund</Button></TableCell></TableRow>{expanded===o.id&&<TableRow><TableCell colSpan={11} className="bg-muted/30"><div className="grid gap-2 p-3 md:grid-cols-3">{(o.order_items??[]).map(i=><div key={i.id} className="rounded-md border border-border bg-background p-3 text-sm"><p className="font-medium">{i.product_name}</p><p className="text-muted-foreground">Qty {i.quantity} · {money(i.unit_price)}</p></div>)}</div></TableCell></TableRow>}</>)}{filtered.length===0&&<TableRow><TableCell colSpan={11} className="py-8 text-center text-muted-foreground">No orders found.</TableCell></TableRow>}</TableBody></Table>}</CardContent></Card>
 <Dialog open={!!cancelFor} onOpenChange={o=>!o&&setCancelFor(null)}><DialogContent><DialogHeader><DialogTitle>Cancel and refund</DialogTitle></DialogHeader><Textarea placeholder="Reason" value={reason} onChange={e=>setReason(e.target.value)}/><DialogFooter><Button variant="outline" onClick={()=>setCancelFor(null)}>Back</Button><Button variant="destructive" onClick={cancel}>Cancel order</Button></DialogFooter></DialogContent></Dialog>
 </div>;
};
const Stat=({label,value}:{label:string;value:number})=><Card><CardContent className="p-5"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 font-display text-3xl">{value}</p></CardContent></Card>;
export default AdminOrders;
