import {  useEffect, useMemo, useState  } from "react";
import { usePageSEO } from "@/hooks/usePageSEO";
import { ExternalLink, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { ReportSummaryButton } from "@/components/ai/ReportSummaryButton";

type Address={name?:string;phone?:string;address?:string;city?:string;state?:string;pincode?:string};
type Rx={id:string;user_id:string|null;guest_name:string|null;guest_phone:string|null;prescription_urls:string[];delivery_address:Address;notes:string|null;status:string|null;quoted_amount:number|null;created_at:string|null;patient?:{full_name?:string|null;phone?:string|null}|null};
const tabs=["all","pending_review","quoted","confirmed","dispatched","delivered","cancelled"];
const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n||0);

const AdminPrescriptions=()=>{
  usePageSEO({ title: "Prescription Orders — Admin", noIndex: true });const [rows,setRows]=useState<Rx[]>([]);const [loading,setLoading]=useState(true);const [tab,setTab]=useState("all");const [quoteFor,setQuoteFor]=useState<Rx|null>(null);const [amount,setAmount]=useState("");const [waybillFor,setWaybillFor]=useState<Rx|null>(null);const [waybill,setWaybill]=useState("");
 const load=async()=>{setLoading(true);const {data,error}=await (supabase as any).from("prescription_orders").select("*").order("created_at",{ascending:false}).limit(300);if(error)toast.error(error.message);const list=(data??[]) as Rx[];const ids=[...new Set(list.map(r=>r.user_id).filter(Boolean))];const {data:profiles}=ids.length?await supabase.from("profiles").select("user_id,full_name,phone").in("user_id",ids):{data:[]} as any;const map=new Map((profiles??[]).map((p:any)=>[p.user_id,p]));setRows(list.map(r=>({...r,patient:r.user_id?map.get(r.user_id)??null:null})));setLoading(false);};
 useEffect(() => { load();},[]); const filtered=useMemo(()=>tab==="all"?rows:rows.filter(r=>(r.status??"pending_review")===tab),[rows,tab]);
 const signed=async(path:string)=>{const {data,error}=await supabase.storage.from("prescriptions").createSignedUrl(path,900);if(error)return toast.error(error.message);window.open(data.signedUrl,"_blank","noreferrer");};
 const update=async(id:string,patch:Record<string,unknown>)=>{const {error}=await (supabase as any).from("prescription_orders").update(patch).eq("id",id);if(error)return toast.error(error.message);toast.success("Prescription order updated");load();};
 const sendQuote=async()=>{if(!quoteFor||!amount)return;await update(quoteFor.id,{quoted_amount:Number(amount),status:"quoted"});const phone=quoteFor.patient?.phone||quoteFor.guest_phone; if(phone)await supabase.functions.invoke("send-whatsapp",{body:{to:phone,message:`Your prescription quote is ready: ₹${Number(amount).toLocaleString("en-IN")}. Tap to confirm your order.`}});setQuoteFor(null);setAmount("");};
 return <div className="space-y-6"><div><h1 className="font-display text-3xl">Prescription Orders</h1><p className="text-sm text-muted-foreground">Review prescriptions, quote patients, and manage dispatch.</p></div><Tabs value={tab} onValueChange={setTab}><TabsList className="flex h-auto flex-wrap justify-start">{tabs.map(t=><TabsTrigger key={t} value={t}>{t==="all"?"All":t.replace(/_/g," ")}</TabsTrigger>)}</TabsList></Tabs>
 <Card><CardContent className="p-0">{loading?<div className="grid place-items-center py-12"><Loader2 className="h-6 w-6 animate-spin"/></div>:<Table><TableHeader><TableRow><TableHead>Patient</TableHead><TableHead>Phone</TableHead><TableHead>Prescription</TableHead><TableHead>Address</TableHead><TableHead>Notes</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Quote</TableHead><TableHead>Submitted</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{filtered.map(r=>{const status=r.status??"pending_review";const phone=r.patient?.phone||r.guest_phone||"—";return <TableRow key={r.id}><TableCell>{r.patient?.full_name||r.guest_name||r.delivery_address?.name||"Patient"}</TableCell><TableCell>{phone}</TableCell><TableCell><div className="space-y-2">{(r.prescription_urls??[]).map((u,i)=><div key={u} className="flex flex-wrap items-center gap-1.5"><Button size="sm" variant="outline" onClick={()=>signed(u)}>Image {i+1}<ExternalLink className="ml-1 h-3 w-3"/></Button><ReportSummaryButton bucket="prescriptions" path={u} fileName={`Prescription ${i+1}`} patientId={r.user_id} refTable="prescription_orders" refId={r.id} documentKind="patient-submitted prescription" variant="inline" /></div>)}</div></TableCell><TableCell className="max-w-xs text-sm">{[r.delivery_address?.address,r.delivery_address?.city,r.delivery_address?.state,r.delivery_address?.pincode].filter(Boolean).join(", ")}</TableCell><TableCell className="max-w-xs truncate">{r.notes??"—"}</TableCell><TableCell><Badge variant={status==="cancelled"?"destructive":"secondary"}>{status.replace(/_/g," ")}</Badge></TableCell><TableCell className="text-right font-semibold">{r.quoted_amount?money(r.quoted_amount):"—"}</TableCell><TableCell>{r.created_at?new Date(r.created_at).toLocaleDateString("en-IN"):"—"}</TableCell><TableCell className="text-right whitespace-nowrap space-x-1">{status==="pending_review"&&<Button size="sm" onClick={()=>{setQuoteFor(r);setAmount(String(r.quoted_amount??""));}}>Enter quote</Button>}{status==="quoted"&&<><Button size="sm" onClick={()=>update(r.id,{status:"confirmed"})}>Confirm</Button><Button size="sm" variant="outline" onClick={()=>update(r.id,{status:"cancelled"})}>Cancel</Button></>}{status==="confirmed"&&<><Button size="sm" onClick={()=>setWaybillFor(r)}>Dispatch</Button><Button size="sm" variant="outline" onClick={()=>update(r.id,{status:"delivered"})}>Delivered</Button></>}{status==="dispatched"&&<Button size="sm" onClick={()=>update(r.id,{status:"delivered"})}>Delivered</Button>}</TableCell></TableRow>})}{filtered.length===0&&<TableRow><TableCell colSpan={9} className="py-8 text-center text-muted-foreground">No prescription orders found.</TableCell></TableRow>}</TableBody></Table>}</CardContent></Card>
 <Dialog open={!!quoteFor} onOpenChange={o=>!o&&setQuoteFor(null)}><DialogContent><DialogHeader><DialogTitle>Enter quoted amount</DialogTitle></DialogHeader><Input type="number" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Quoted amount"/><DialogFooter><Button variant="outline" onClick={()=>setQuoteFor(null)}>Back</Button><Button onClick={sendQuote} disabled={!amount}>Send quote</Button></DialogFooter></DialogContent></Dialog>
 <Dialog open={!!waybillFor} onOpenChange={o=>!o&&setWaybillFor(null)}><DialogContent><DialogHeader><DialogTitle>Mark as dispatched</DialogTitle></DialogHeader><Input value={waybill} onChange={e=>setWaybill(e.target.value)} placeholder="Waybill number"/><DialogFooter><Button variant="outline" onClick={()=>setWaybillFor(null)}>Back</Button><Button onClick={()=>{if(waybillFor)update(waybillFor.id,{status:"dispatched",admin_note:waybill?`Waybill: ${waybill}`:null});setWaybillFor(null);setWaybill("");}}>Dispatch</Button></DialogFooter></DialogContent></Dialog>
 </div>};
export default AdminPrescriptions;
